CREATE TABLE [dbo].[BrandCostAnalysis] (
    [ID]            VARCHAR (13)    NULL,
    [MrTeam]        VARCHAR (5)     NULL,
    [Category]      VARCHAR (10)    NULL,
    [BrandID]       VARCHAR (8)     NULL,
    [StyleID]       VARCHAR (15)    NULL,
    [SeasonID]      VARCHAR (10)    NULL,
    [SeasonSCIID]   VARCHAR (10)    NULL,
    [ProgramID]     VARCHAR (12)    NULL,
    [FactoryID]     VARCHAR (8)     NULL,
    [CdCodeID]      VARCHAR (6)     NULL,
    [OrderQty]      NUMERIC (6)     NULL,
    [QuotCost]      NUMERIC (6, 3)  NULL,
    [QuotAmt]       NUMERIC (10, 2) NULL,
    [FOB]           NUMERIC (6, 2)  NULL,
    [FOBAmt]        NUMERIC (10, 2) NULL,
    [POAmt]         NUMERIC (10, 2) NULL,
    [CMP]           NUMERIC (8, 3)  NULL,
    [CMPAmt]        NUMERIC (10, 2) NULL,
    [InputAmt]      NUMERIC (10, 2) NULL,
    [StockAmt]      NUMERIC (10, 2) NULL,
    [ActPOAmt]      NUMERIC (10, 2) NULL,
    [FtyCost]       NUMERIC (6, 3)  NULL,
    [FtyCostAmt]    NUMERIC (10, 2) NULL,
    [Apparel]       VARCHAR (500)   NULL,
    [Gender]        VARCHAR (10)    NULL,
    [Lining]        VARCHAR (MAX)   NULL,
    [FabricType]    VARCHAR (5)     NULL,
    [StyleUnit]     VARCHAR (8)     NULL,
    [YYYYMM]        VARCHAR (6)     NULL,
    [BuyerDelivery] DATE            NULL,
    [SCIDelivery]   DATE            NULL
);

