CREATE TABLE [dbo].[ForecastLoadingBI](
	[StyleUkey] [bigint] NULL,
	[Factory] [varchar](8) NULL,
	[FtyCountryID] [varchar](2) NULL,
	[MDivisionID] [varchar](8) NULL,
	[BuyerDelivery] [date] NULL,
	[SCIDelivery] [date] NULL,
	[Key] [varchar](6) NULL,
	[HalfKey] [varchar](8) NULL,
	[Category] [varchar](50) NULL,
	[DevSample] [varchar](1) NULL,
	[PONO] [varchar](30) NULL,
	[POID] [varchar](30) NULL,
	[SPNO] [varchar](13) NULL,
	[StyleID] [varchar](15) NULL,
	[Season] [varchar](10) NULL,
	[Brand] [varchar](8) NULL,
	[Program] [varchar](12) NULL,
	[CDCodeID] [varchar](6) NULL,
	[ProductionFamilyID] [varchar](20) NULL,
	[CPU] [numeric](8, 3) NULL,
	[Qty] [numeric](6, 0) NULL,
	[TTLCPU] [numeric](36, 4) NULL,
	[Junk] [varchar](1) NULL,
	[TTL_AT (CPU)] [numeric](38, 6) NULL,
	[TTL_AT (HAND) (CPU)] [numeric](38, 6) NULL,
	[TTL_AT (MACHINE) (CPU)] [numeric](38, 6) NULL,
	[TTL_AUTO-TEMPLATE (CPU)] [numeric](38, 6) NULL,
	[TTL_B-HOT PRESS(BONDING) (CPU)] [numeric](38, 6) NULL,
	[TTL_BIG HOT PRESS (CPU)] [numeric](38, 6) NULL,
	[TTL_BONDING (HAND) (CPU)] [numeric](38, 6) NULL,
	[TTL_BONDING (MACHINE) (CPU)] [numeric](38, 6) NULL,
	[TTL_CUTTING (CPU)] [numeric](38, 6) NULL,
	[TTL_DIE CUT (CPU)] [numeric](38, 6) NULL,
	[TTL_DIE-CUT (CPU)] [numeric](38, 6) NULL,
	[TTL_DOWN (CPU)] [numeric](38, 6) NULL,
	[TTL_DOWN FILLING (CPU)] [numeric](38, 6) NULL,
	[TTL_EMBOSS/DEBOSS (Price)] [numeric](38, 6) NULL,
	[TTL_EMBROIDERY (Price)] [numeric](38, 6) NULL,
	[TTL_EMBROIDERY (STITCH in thousands)] [numeric](38, 6) NULL,
	[TTL_EYEBUTTON (CPU)] [numeric](38, 6) NULL,
	[TTL_FEEDOFARM (CPU)] [numeric](38, 6) NULL,
	[TTL_Fusible (CPU)] [numeric](38, 6) NULL,
	[TTL_GARMENT DYE (Price)] [numeric](38, 6) NULL,
	[TTL_GMT WASH (Price)] [numeric](38, 6) NULL,
	[TTL_HEAT TRANSFER (CPU)] [numeric](38, 6) NULL,
	[TTL_INSPECTION (CPU)] [numeric](38, 6) NULL,
	[TTL_INTENSIVE MACHINE (CPU)] [numeric](38, 6) NULL,
	[TTL_LASER (CPU)] [numeric](38, 6) NULL,
	[TTL_LASER CUTTER (CPU)] [numeric](38, 6) NULL,
	[TTL_PAD PRINTING (Price)] [numeric](38, 6) NULL,
	[TTL_PRINTING (PCS)] [numeric](38, 6) NULL,
	[TTL_PRINTING (Price)] [numeric](38, 6) NULL,
	[TTL_REAL FLATSEAM (CPU)] [numeric](38, 6) NULL,
	[TTL_ROLLER SUBLIMATION (CPU)] [numeric](38, 6) NULL,
	[TTL_S-HOT PRESS(BONDING) (CPU)] [numeric](38, 6) NULL,
	[TTL_S-HOT PRESS(HT) (CPU)] [numeric](38, 6) NULL,
	[TTL_SEAM TAPING MACHINE (CPU)] [numeric](38, 6) NULL,
	[TTL_SMALL HOT PRESS (CPU)] [numeric](38, 6) NULL,
	[TTL_SUBLIMATION PRINT (CPU)] [numeric](38, 6) NULL,
	[TTL_SUBLIMATION ROLLER (CPU)] [numeric](38, 6) NULL,
	[TTL_ULTRASONIC MACHINE (CPU)] [numeric](38, 6) NULL,
	[TTL_VELCRO MACHINE (CPU)] [numeric](38, 6) NULL,
	[TTL_ZIG ZAG (CPU)] [numeric](38, 6) NULL, 
    [Sew_Qty] NUMERIC(6) NULL, 
    [Shortage] NUMERIC(6) NULL, 
    [Buyer Key] VARCHAR(6) NULL, 
    [Buyer HalfKey] VARCHAR(8) NULL, 
    [Sew_Qty by Rate] NUMERIC(10, 4) NULL
) ON [PRIMARY]
GO