CREATE TABLE [dbo].[ForecastLoadingBI](
		[StyleUkey] [bigint],
		[Factory] [varchar](8),
		[FtyCountryID] [varchar](2),
		[MDivisionID] [varchar](8),
		[BuyerDelivery] [date],
		[SCIDelivery] [date],
		[Key] [varchar](6),
		[HalfKey] [varchar](8),
		[Buyer Key] [varchar](6),
		[Buyer HalfKey] [varchar](8),
		[Category] [varchar](50),
		[DevSample] [varchar](1),
		[PONO] [varchar](30),
		[POID] [varchar](30),
		[SPNO] [varchar](13),
		[StyleID] [varchar](15),
		[Season] [varchar](10),
		[Brand] [varchar](8),
		[Program] [varchar](12),
		[CDCodeID] [varchar](6),
		[ProductionFamilyID] [varchar](20),
		[CPU] [numeric](8, 3),
		[Qty] [numeric](6, 0),
		[TTLCPU] [numeric](36, 4),
		[Junk] [varchar](1),
		[Need Production] [varchar](1),
		[Keep Panels] [varchar](1),
		[Buy Back] [varchar](1),
		[Buy Back Reason] [varchar](20),
		[TTL_AT (CPU)] [numeric](38, 6),
		[TTL_AT (HAND) (CPU)] [numeric](38, 6),
		[TTL_AT (MACHINE) (CPU)] [numeric](38, 6),
		[TTL_AUTO-TEMPLATE (CPU)] [numeric](38, 6),
		[TTL_B-HOT PRESS(BONDING) (CPU)] [numeric](38, 6),
		[TTL_BIG HOT PRESS (CPU)] [numeric](38, 6),
		[TTL_BONDING (HAND) (CPU)] [numeric](38, 6),
		[TTL_BONDING (MACHINE) (CPU)] [numeric](38, 6),
		[TTL_CUTTING (CPU)] [numeric](38, 6),
		[TTL_DIE CUT (CPU)] [numeric](38, 6),
		[TTL_DIE-CUT (CPU)] [numeric](38, 6),
		[TTL_DOWN (CPU)] [numeric](38, 6),
		[TTL_DOWN FILLING (CPU)] [numeric](38, 6),
		[TTL_EMBOSS/DEBOSS (Price)] [numeric](38, 6),
		[TTL_EMBROIDERY (Price)] [numeric](38, 6),
		[TTL_EMBROIDERY (STITCH in thousands)] [numeric](38, 6),
		[TTL_EYEBUTTON (CPU)] [numeric](38, 6),
		[TTL_FEEDOFARM (CPU)] [numeric](38, 6),
		[TTL_Fusible (CPU)] [numeric](38, 6),
		[TTL_GARMENT DYE (Price)] [numeric](38, 6),
		[TTL_GMT WASH (Price)] [numeric](38, 6),
		[TTL_HEAT TRANSFER (CPU)] [numeric](38, 6),
		[TTL_INSPECTION (CPU)] [numeric](38, 6),
		[TTL_INTENSIVE MACHINE (CPU)] [numeric](38, 6),
		[TTL_LASER (CPU)] [numeric](38, 6),
		[TTL_LASER CUTTER (CPU)] [numeric](38, 6),
		[TTL_PAD PRINTING (Price)] [numeric](38, 6),
		[TTL_PRINTING (PCS)] [numeric](38, 6),
		[TTL_PRINTING (Price)] [numeric](38, 6),
		[TTL_REAL FLATSEAM (CPU)] [numeric](38, 6),
		[TTL_ROLLER SUBLIMATION (CPU)] [numeric](38, 6),
		[TTL_S-HOT PRESS(BONDING) (CPU)] [numeric](38, 6),
		[TTL_S-HOT PRESS(HT) (CPU)] [numeric](38, 6),
		[TTL_SEAM TAPING MACHINE (CPU)] [numeric](38, 6),
		[TTL_SMALL HOT PRESS (CPU)] [numeric](38, 6),
		[TTL_SUBLIMATION PRINT (CPU)] [numeric](38, 6),
		[TTL_SUBLIMATION ROLLER (CPU)] [numeric](38, 6),
		[TTL_ULTRASONIC MACHINE (CPU)] [numeric](38, 6),
		[TTL_VELCRO MACHINE (CPU)] [numeric](38, 6),
		[TTL_ZIG ZAG (CPU)] [numeric](38, 6),
		[TTL_PRINTING PPU (PPU)] [numeric](38, 6),
		[Sew_Qty by Rate] [numeric](10, 4),
		[Sew_Qty] [numeric](6, 0),
		[Shortage] [numeric](6, 0),
		[Project] [varchar](5),
		[CustDate] [date], 
		[KPI L/ETA] DATE NULL, 
		[LastProductionDate] DATE NULL
) ON [PRIMARY]
GO