CREATE TABLE [dbo].[InventoryAnalysis] (
    [RowNo]            BIGINT          NULL,
    [MrTeam]           VARCHAR (5)     NULL,
    [Brand]            VARCHAR (8)     NULL,
    [Stlye]            VARCHAR (15)    NULL,
    [Season]           VARCHAR (10)    NULL,
    [SeasonYear]       VARCHAR (7)     NULL,
    [POID]             VARCHAR (13)    NULL,
    [Seq1]             VARCHAR (3)     NULL,
    [Seq2]             VARCHAR (2)     NULL,
    [InvReason]        VARCHAR (5)     NULL,
    [InvReasonCNM]     NVARCHAR (MAX)  NULL,
    [InvReasonENM]     NVARCHAR (MAX)  NULL,
    [Program]          VARCHAR (12)    NULL,
    [Project]          VARCHAR (30)    NULL,
    [Price]            NUMERIC (16, 4) NULL,
    [IsFoc]            VARCHAR (15)    NULL,
    [Qty]              NUMERIC (10, 2) NULL,
    [ChargeStatus]     VARCHAR (1)     NULL,
    [ChargeStatusNM]   VARCHAR (20)    NULL,
    [Amount]           NUMERIC (16, 2) NULL,
    [Amount_WithouFOC] NUMERIC (16, 2) NULL,
    [FOBCharge]        NUMERIC (16, 2) NULL,
    [SuppGroup]        VARCHAR (60)    NULL,
    [Supplier]         VARCHAR (60)    NULL,
    [Currency]         VARCHAR (3)     NULL,
    [ToCurrency]       VARCHAR (3)     NULL,
    [MtlDesc]          NVARCHAR (MAX)  NULL,
    [ETD]              DATE            NULL,
    [RefNo]            VARCHAR (36)    NULL,
    [SCIRefNo]         VARCHAR (30)    NULL,
    [FabricType]       VARCHAR (10)    NULL,
    [MaterialType]     VARCHAR (20)    NULL,
    [Color]            NVARCHAR (MAX)  NULL,
    [SizeSpec]         VARCHAR (15)    NULL,
    [SizeUnit]         VARCHAR (8)     NULL,
    [Deadline]         VARCHAR (10)    NULL,
    [OrderSMR]         NVARCHAR (70)   NULL,
    [OrderHandle]      NVARCHAR (70)   NULL,
    [POSMR]            NVARCHAR (70)   NULL,
    [POHandle]         NVARCHAR (70)   NULL,
    [POSMRNM]          NVARCHAR (50)   NULL,
    [OrderSMRNM]       NVARCHAR (50)   NULL
);

