CREATE TABLE [dbo].[OrderComparison_Detail] (
    [MrTeam]              VARCHAR (5)     NULL,
    [Brand]               VARCHAR (8)     NULL,
    [Style]               VARCHAR (15)    NULL,
    [Season]              VARCHAR (10)    NULL,
    [SeasonSCI]           VARCHAR (10)    NULL,
    [OrderID]             VARCHAR (13)    NULL,
    [CFMDate]             DATE            NULL,
    [CFMYM]               VARCHAR (6)     NULL,
    [CFMYear]             VARCHAR (4)     NULL,
    [CFMYM_L]             VARCHAR (6)     NULL,
    [CFMYear_L]           VARCHAR (4)     NULL,
    [CFMMonth]            VARCHAR (2)     NULL,
    [CFMMonthNM]          VARCHAR (30)    NULL,
    [Category]            VARCHAR (30)    NULL,
    [Project]             VARCHAR (5)     NULL,
    [Program]             VARCHAR (12)    NULL,
    [CdCode]              VARCHAR (100)   NULL,
    [ApparelType]         VARCHAR (50)    NULL,
    [FabricType]          VARCHAR (5)     NULL,
    [Factory]             VARCHAR (8)     NULL,
    [FactoryCountry]      VARCHAR (2)     NULL,
    [Destination]         VARCHAR (2)     NULL,
    [Currency]            VARCHAR (3)     NULL,
    [SMR]                 VARCHAR (10)    NULL,
    [SMRNM]               VARCHAR (150)   NULL,
    [MRHandle]            VARCHAR (10)    NULL,
    [MRHandleNM]          VARCHAR (150)   NULL,
    [CfmPrice]            NUMERIC (16, 4) NULL,
    [CPU]                 NUMERIC (8, 3)  NULL,
    [Qty]                 NUMERIC (6)     NULL,
    [OrderAmt]            NUMERIC (16, 2) NULL,
    [OrderSurcharge]      NUMERIC (16, 2) NULL,
    [OrderTotalAmt]       NUMERIC (16, 2) NULL,
    [OrderAmt_FX]         NUMERIC (16, 2) NULL,
    [OrderSurcharge_FX]   NUMERIC (16, 2) NULL,
    [OrderTotalAmt_FX]    NUMERIC (16, 2) NULL,
    [OrderComparisonUkey] BIGINT          NULL
);

