CREATE TABLE [dbo].[P_AdiCompReport] (
    [Year]           VARCHAR (4)    NULL,
    [Month]          VARCHAR (2)    NULL,
    [ID]             VARCHAR (13)   NULL,
    [SalesID]        VARCHAR (5)    NULL,
    [SalesName]      NVARCHAR (50)  NULL,
    [Article]        VARCHAR (8)    NULL,
    [ArticleName]    NVARCHAR (60)  NULL,
    [ProductionDate] DATE           NULL,
    [DefectMainID]   VARCHAR (2)    NULL,
    [DefectSubID]    VARCHAR (1)    NULL,
    [FOB]            NUMERIC (5, 2) NULL,
    [Qty]            NUMERIC (3)    NULL,
    [ValueinUSD]     NUMERIC (8, 4) NULL,
    [ValueINExRate]  NUMERIC (7, 2) NULL,
    [OrderID]        VARCHAR (13)   NULL,
    [RuleNo]         NUMERIC (1)    NULL,
    [UKEY]           BIGINT         NULL,
    [BrandID]        VARCHAR (8)    NULL,
    [FactoryID]      VARCHAR (8)    NULL,
    [SuppID]         VARCHAR (6)    NULL,
    [Refno]          VARCHAR (36)   NULL,
    [IsEM]           BIT            NULL,
    [StyleID]        VARCHAR (15)   NULL,
    [ProgramID]      VARCHAR (12)   NULL,
    [Supplier]       VARCHAR (6)    NULL,
    [SupplierName]   NVARCHAR (12)  NULL,
    [DefectMain]     NVARCHAR (260) NULL,
    [DefectSub]      NVARCHAR (260) NULL,
    [Responsibility] VARCHAR (2)    NULL,
    [MDivisionID]    VARCHAR (8)    NULL
);

