CREATE TABLE [dbo].[P_Credit](
	[ID] [varchar](13) NOT NULL,
	[Status] [varchar](15) NULL,
	[CDate] [date] NULL,
	[SentDate] [datetime] NULL,
	[BrandID] [varchar](13) NULL,
	[Buyer] [varchar](8) NULL,
	[Onwer] [varchar](40) NULL,
	[Name] [nvarchar](60) NULL,
	[Reason] [nvarchar](500) NULL,
	[Subject] [nvarchar](100) NULL,
	[Description] [varchar](max) NULL,
	[VoucherDate] [date] NULL,
	[Responsibility] [nvarchar](50) NULL,
	[Incharge] [varchar](10) NULL,
	[SourceID] [varchar](13) NULL,
	[OrderID] [varchar](13) NULL,
	[POID] [varchar](30) NULL,
	[StyleID] [varchar](15) NULL,
	[CustCDID] [varchar](16) NULL,
	[OrderQty] [numeric](6, 0) NOT NULL,
	[BuyerDelivery] [date] NULL,
	[pulloutdate] [date] NULL,
	[PulloutQty] [numeric](9, 0) NULL,
	[Unit] [varchar](8) NULL,
	[PulloutAmount] [numeric](18, 2) NOT NULL,
	[Qty] [numeric](9, 0) NOT NULL,
	[Amount] [numeric](9, 3) NOT NULL,
	[Remark] [varchar](30) NULL,
	[DebitID] [varchar](13) NULL,
	[ReceivedDate] [nvarchar](max) NULL,
	[Destination] [nvarchar](30) NULL,
	[Supplier/Subcon name] [varchar](30) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO