CREATE TABLE [dbo].[P_CuttingScheduleOutputList] (
    [MDivisionID]           VARCHAR (8)     CONSTRAINT [DF_P_CuttingScheduleOutputList_MDivisionID] DEFAULT ('') NOT NULL,
    [FactoryID]             VARCHAR (8)     CONSTRAINT [DF_P_CuttingScheduleOutputList_FactoryID] DEFAULT ('') NOT NULL,
    [Fabrication]           VARCHAR (20)    CONSTRAINT [DF_P_CuttingScheduleOutputList_Fabrication] DEFAULT ('') NOT NULL,
    [EstCuttingDate]        DATE            NULL,
    [ActCuttingDate]        DATE            NULL,
    [EarliestSewingInline]  DATE            NULL,
    [POID]                  VARCHAR (13)    CONSTRAINT [DF_P_CuttingScheduleOutputList_POID] DEFAULT ('') NOT NULL,
    [BrandID]               VARCHAR (8)     CONSTRAINT [DF_P_CuttingScheduleOutputList_BrandID] DEFAULT ('') NOT NULL,
    [StyleID]               VARCHAR (15)    CONSTRAINT [DF_P_CuttingScheduleOutputList_StyleID] DEFAULT ('') NOT NULL,
    [FabRef]                VARCHAR (36)    CONSTRAINT [DF_P_CuttingScheduleOutputList_FabRef] DEFAULT ('') NOT NULL,
    [SwitchToWorkorderType] VARCHAR (11)    CONSTRAINT [DF_P_CuttingScheduleOutputList_SwitchToWorkorderType] DEFAULT ('') NOT NULL,
    [CutRef]                VARCHAR (10)     CONSTRAINT [DF_P_CuttingScheduleOutputList_CutRef] DEFAULT ('') NOT NULL,
    [CutNo]                 NUMERIC (6)     CONSTRAINT [DF_P_CuttingScheduleOutputList_CutNo] DEFAULT ((0)) NOT NULL,
    [SpreadingNoID]         VARCHAR (5)     CONSTRAINT [DF_P_CuttingScheduleOutputList_SpreadingNoID] DEFAULT ('') NOT NULL,
    [CutCell]               VARCHAR (2)     CONSTRAINT [DF_P_CuttingScheduleOutputList_CutCell] DEFAULT ('') NOT NULL,
    [Combination]           VARCHAR (2)     CONSTRAINT [DF_P_CuttingScheduleOutputList_Combination] DEFAULT ('') NOT NULL,
    [Layers]                NUMERIC (5)     CONSTRAINT [DF_P_CuttingScheduleOutputList_Layers] DEFAULT ((0)) NOT NULL,
    [LayersLevel]           VARCHAR (10)    CONSTRAINT [DF_P_CuttingScheduleOutputList_LayersLevel] DEFAULT ('') NOT NULL,
    [LackingLayers]         NUMERIC (10)    CONSTRAINT [DF_P_CuttingScheduleOutputList_LackingLayers] DEFAULT ((0)) NOT NULL,
    [Ratio]                 VARCHAR (MAX)   NOT NULL,
    [Consumption]           NUMERIC (9, 4)  CONSTRAINT [DF_P_CuttingScheduleOutputList_Consumption] DEFAULT ((0)) NOT NULL,
    [ActConsOutput]         NUMERIC (10, 4) CONSTRAINT [DF_P_CuttingScheduleOutputList_ActConsOutput] DEFAULT ((0)) NOT NULL,
    [BalanceCons]           NUMERIC (10, 4) CONSTRAINT [DF_P_CuttingScheduleOutputList_BalanceCons] DEFAULT ((0)) NOT NULL,
    [MarkerName]            VARCHAR (20)    CONSTRAINT [DF_P_CuttingScheduleOutputList_MarkerName] DEFAULT ('') NOT NULL,
    [MarkerNo]              VARCHAR (10)    CONSTRAINT [DF_P_CuttingScheduleOutputList_MarkerNo] DEFAULT ('') NOT NULL,
    [MarkerLength]          VARCHAR (15)    CONSTRAINT [DF_P_CuttingScheduleOutputList_MarkerLength] DEFAULT ('') NOT NULL,
    [CuttingPerimeter]      NVARCHAR (15)   CONSTRAINT [DF_P_CuttingScheduleOutputList_CuttingPerimeter] DEFAULT ('') NOT NULL,
    [StraightLength]        VARCHAR (15)    CONSTRAINT [DF_P_CuttingScheduleOutputList_StraightLength] DEFAULT ('') NOT NULL,
    [CurvedLength]          VARCHAR (15)    CONSTRAINT [DF_P_CuttingScheduleOutputList_CurvedLength] DEFAULT ('') NOT NULL,
    [DelayReason]           NVARCHAR (100)  CONSTRAINT [DF_P_CuttingScheduleOutputList_DelayReason] DEFAULT ('') NOT NULL,
    [Remark]                NVARCHAR (MAX)  CONSTRAINT [DF_P_CuttingScheduleOutputList_Remark] DEFAULT ('') NOT NULL,
    [Ukey]                  BIGINT          IDENTITY (1, 1) NOT NULL,
    CONSTRAINT [PK_P_CuttingScheduleOutputList] PRIMARY KEY CLUSTERED ([Ukey] ASC)
);

