CREATE TABLE [dbo].[P_CuttingScheduleOutputList]
(
	[MDivisionID] VARCHAR(8) NOT NULL DEFAULT (('')), 
    [FactoryID] VARCHAR(8) NOT NULL DEFAULT (('')), 
    [Fabrication] VARCHAR(20) NOT NULL DEFAULT (('')), 
    [EstCuttingDate] DATE NULL, 
    [ActCuttingDate] DATE NULL, 
    [EarliestSewingInline] DATE NULL, 
    [POID] VARCHAR(13) NOT NULL DEFAULT (('')), 
    [BrandID] VARCHAR(8) NOT NULL DEFAULT (('')), 
    [StyleID] VARCHAR(15) NOT NULL DEFAULT (('')), 
    [FabRef] VARCHAR(36) NOT NULL DEFAULT (('')), 
    [SwitchToWorkorderType] VARCHAR(11) NOT NULL DEFAULT (('')), 
    [CutRef] VARCHAR(6) NOT NULL DEFAULT (('')), 
    [CutNo] NUMERIC(6) NOT NULL DEFAULT ((0)), 
    [SpreadingNoID] VARCHAR(5) NOT NULL DEFAULT (('')), 
    [CutCell] VARCHAR(2) NOT NULL DEFAULT (('')), 
    [Combination] VARCHAR(2) NOT NULL DEFAULT (('')), 
    [Layers] NUMERIC(5) NOT NULL DEFAULT ((0)), 
    [LayersLevel] VARCHAR(10) NOT NULL DEFAULT (('')), 
    [LackingLayers] NUMERIC(10) NOT NULL DEFAULT ((0)), 
    [Ratio] VARCHAR(50) NOT NULL DEFAULT (('')), 
    [Consumption] NUMERIC(9, 4) NOT NULL DEFAULT ((0)), 
    [ActConsOutput] VARCHAR(20) NOT NULL DEFAULT (('')), 
    [BalanceCons] VARCHAR(20) NOT NULL DEFAULT (('')), 
    [MarkerName] VARCHAR(20) NOT NULL DEFAULT (('')), 
    [MarkerNo] VARCHAR(10) NOT NULL DEFAULT (('')), 
    [MarkerLength] VARCHAR(15) NOT NULL DEFAULT (('')), 
    [CuttingPerimeter] NVARCHAR(15) NOT NULL DEFAULT (('')), 
    [StraightLength] VARCHAR(15) NOT NULL DEFAULT (('')), 
    [CurvedLength] VARCHAR(15) NOT NULL DEFAULT (('')), 
    [DelayReason] NVARCHAR(100) NOT NULL DEFAULT (('')), 
    [Remark] NVARCHAR(MAX) NOT NULL DEFAULT (('')), 
    [Ukey] BIGINT IDENTITY (1,1), 
    CONSTRAINT [PK_P_CuttingScheduleOutputList] PRIMARY KEY ([Ukey]) 
)
