CREATE TABLE [dbo].[P_DailyAccuCPULoading]
(
	 [Year]								varchar(4)		CONSTRAINT [DF_P_DailyAccuCPULoading_Year]	NOT NULL DEFAULT ((''))
	,[Month]							varchar(2)		CONSTRAINT [DF_P_DailyAccuCPULoading_Month]	NOT NULL DEFAULT ((''))
	,[FactoryID]						varchar(8)		CONSTRAINT [DF_P_DailyAccuCPULoading_FactoryId]	NOT NULL DEFAULT ((''))
	,[TTLCPULoaded]						int				CONSTRAINT [DF_P_DailyAccuCPULoading_TTLCPULoaded]	NOT NULL DEFAULT ((0))
	,[UnfinishedLastMonth]				int				CONSTRAINT [DF_P_DailyAccuCPULoading_UnfinishedLastMonth]	NOT NULL DEFAULT ((0))
	,[FinishedLastMonth]				int				CONSTRAINT [DF_P_DailyAccuCPULoading_FinishedLastMonth]	NOT NULL DEFAULT ((0))
	,[CanceledStillNeedProd]			int				CONSTRAINT [DF_P_DailyAccuCPULoading_CanceledStillNeedProd]	NOT NULL DEFAULT ((0))
	,[SubconToSisFactory]				int				CONSTRAINT [DF_P_DailyAccuCPULoading_SubconToSisFactory]	NOT NULL DEFAULT ((0))
	,[SubconFromSisterFactory]			int				CONSTRAINT [DF_P_DailyAccuCPULoading_SubconFromSisterFactory]	NOT NULL DEFAULT ((0))
	,[PullForwardFromNextMonths]		int				CONSTRAINT [DF_P_DailyAccuCPULoading_PullForwardFromNextMonths]	NOT NULL DEFAULT ((0))
	,[LoadingDelayFromThisMonth]		int				CONSTRAINT [DF_P_DailyAccuCPULoading_LoadingDelayFromThisMonth]	NOT NULL DEFAULT ((0))
	,[LocalSubconInCPU]					int				CONSTRAINT [DF_P_DailyAccuCPULoading_LocalSubconInCPU]	NOT NULL DEFAULT ((0))
	,[LocalSubconOutCPU]				int				CONSTRAINT [DF_P_DailyAccuCPULoading_LocalSubconOutCPU]	NOT NULL DEFAULT ((0))
	,[RemainCPUThisMonth]				int				CONSTRAINT [DF_P_DailyAccuCPULoading_RemainCPUThisMonth]	NOT NULL DEFAULT ((0))
	,[AddName]							varchar(10)		CONSTRAINT [DF_P_DailyAccuCPULoading_AddDate]	NOT NULL DEFAULT ((''))
	,[AddDate]							datetime		CONSTRAINT [DF_P_DailyAccuCPULoading_AddDate]	NULL
	,[EditName]							varchar(10)		CONSTRAINT [DF_P_DailyAccuCPULoading_EditName]	NOT NULL DEFAULT ((''))
	,[EditDate]							datetime		CONSTRAINT [DF_P_DailyAccuCPULoading_EditDate]	NULL
	,[Date]								varchar(5)		CONSTRAINT [DF_P_DailyAccuCPULoading_Date]	NOT NULL DEFAULT ((''))
	,[WeekDay]							varchar(3)		CONSTRAINT [DF_P_DailyAccuCPULoading_WeekDay]	NOT NULL DEFAULT ((''))
	,[DailyCPULoading]					int				CONSTRAINT [DF_P_DailyAccuCPULoading_DailyCPULoading]	NOT NULL DEFAULT ((0))
	,[NewTarget]						int				CONSTRAINT [DF_P_DailyAccuCPULoading_NewTarget]	NOT NULL DEFAULT ((0))
	,[ActCPUPerformed]					decimal(8,3)	CONSTRAINT [DF_P_DailyAccuCPULoading_ActCPUPerformed]	NOT NULL DEFAULT ((0))
	,[DailyCPUVarience]					int				CONSTRAINT [DF_P_DailyAccuCPULoading_DailyCPUVarience]	NOT NULL DEFAULT ((0))
	,[AccuLoading]						int				CONSTRAINT [DF_P_DailyAccuCPULoading_AccuLoading]	NOT NULL DEFAULT ((0))
	,[AccuActCPUPerformed]				int				CONSTRAINT [DF_P_DailyAccuCPULoading_AccuActCPUPerformed]	NOT NULL DEFAULT ((0))
	,[AccuCPUVariance]					int				CONSTRAINT [DF_P_DailyAccuCPULoading_AccuCPUVariance]	NOT NULL DEFAULT ((0))
	,[LeftWorkDays]						int				CONSTRAINT [DF_P_DailyAccuCPULoading_LeftWorkDays]	NOT NULL DEFAULT ((0))
	,[AvgWorkhours]						decimal(8,2)	CONSTRAINT [DF_P_DailyAccuCPULoading_AvgWorkhours]	NOT NULL DEFAULT ((0))
	,[PPH]								decimal(8,2)	CONSTRAINT [DF_P_DailyAccuCPULoading_PPH]	NOT NULL DEFAULT ((0))
	,[Direct]							int				CONSTRAINT [DF_P_DailyAccuCPULoading_Direct]	NOT NULL DEFAULT ((0))
	,[Active]							int				CONSTRAINT [DF_P_DailyAccuCPULoading_Active]	NOT NULL DEFAULT ((0))
	,[VPH]								decimal(8,2)	CONSTRAINT [DF_P_DailyAccuCPULoading_VPH]	NOT NULL DEFAULT ((0))
	,[ManpowerRatio]					decimal(8,2)	CONSTRAINT [DF_P_DailyAccuCPULoading_ManpowerRatio]	NOT NULL DEFAULT ((0))
	,[LineNo]							int				CONSTRAINT [DF_P_DailyAccuCPULoading_LineNo]	NOT NULL DEFAULT ((0))
	,[LineManpower]						int				CONSTRAINT [DF_P_DailyAccuCPULoading_LineManpower]	NOT NULL DEFAULT ((0))
	,[GPH]								decimal(8,2)	CONSTRAINT [DF_P_DailyAccuCPULoading_GPH]	NOT NULL DEFAULT ((0))
	,[SPH]								decimal(8,2)	CONSTRAINT [DF_P_DailyAccuCPULoading_SPH]	NOT NULL DEFAULT ((0)),
    CONSTRAINT [PK_P_DailyAccuCPULoading] PRIMARY KEY ([Year],[Month],[FactoryID],[Date])
)
