CREATE TABLE [dbo].[P_DQSDefect_Detail] (
    [FtyZon]              VARCHAR (8)    NULL,
    [BrandID]             VARCHAR (8)    NULL,
    [BuyerDelivery]       DATE           NULL,
    [Line]                VARCHAR (2)    NULL,
    [FactoryID]           VARCHAR (8)    NULL,
    [Team]                VARCHAR (8)    NULL,
    [Shift]               VARCHAR (5)    NULL,
    [POID]                VARCHAR (30)   NULL,
    [StyleID]             VARCHAR (15)   NULL,
    [SPNO]                VARCHAR (13)   NULL,
    [Article]             VARCHAR (8)    NULL,
    [Status]              VARCHAR (7)    NULL,
    [FixType]             VARCHAR (12)   NULL,
    [FirstInspectDate]    DATE           NULL,
    [FirstInspectTime]    TIME (7)       NULL,
    [InspectQCName]       NVARCHAR (30)  NULL,
    [FixedTime]           VARCHAR (16)   NULL,
    [FixedQCName]         NVARCHAR (30)  NULL,
    [ProductType]         VARCHAR (6)    NULL,
    [SizeCode]            VARCHAR (8)    NULL,
    [DefectTypeDesc]      NVARCHAR (60)  NULL,
    [DefectCodeDesc]      NVARCHAR (100) NULL,
    [AreaCode]            VARCHAR (50)   NULL,
    [ReworkCardNo]        VARCHAR (2)    NULL,
    [GarmentDefectTypeID] VARCHAR (1)    NULL,
    [GarmentDefectCodeID] VARCHAR (3)    NULL
);

