CREATE TABLE [dbo].[P_EstShippingReport] (
	[BuyerDelivery] [date] NULL,
	[Brand] [varchar](8) NULL,
	[SPNO] [varchar](13) NULL,
	[Category] [varchar](8) NULL,
	[Seq] [varchar](2) NULL,
	[PackingNo] [varchar](max) NULL,
	[PackingStatus] [varchar](max) NULL,
	[GBNo] [varchar](max) NULL,
	[PulloutDate] [varchar](max) NULL,
	[Order_TtlQty] [int] NULL,
	[SO_No] [varchar](16) NULL,
	[SO_CfmDate] [date] NULL,
	[CutOffDate] [datetime] NULL,
	[ShipPlanID] [varchar](13) NULL,
	[M] [varchar](8) NULL,
	[Factory] [varchar](8) NULL,
	[Destination] [varchar](30) NULL,
	[Price] [numeric](16, 3) NULL,
	[GW] [numeric](8, 3) NULL,
	[CBM] [numeric](13, 4) NULL,
	[ShipMode] [varchar](10) NULL,
	[Handle] [varchar](80) NULL,
	[LocalMR] [varchar](80) NULL,
	[SP_SEQ] [varchar](15) NULL,
	[If_Partial] [varchar](1) NULL,
	[CartonQtyAtCLog] [int] NULL,
	[SP_Prod_Output_Qty] [int] NULL,
	[OrderType] [varchar](20) NULL,
	[BuyBack] [varchar](1) NULL,
	[LoadingType] [varchar](max) NULL,
	[Est_PODD] [date] NULL,
	[Origin] [varchar](2) NULL,
	[Outstanding_Reason2] [nvarchar](800) NULL,
	[Outstanding_Remark] [nvarchar](max) NULL,
	[ReturnedQty_bySeq] [int] NULL,
	[HC#] [varchar](max) NULL,
	[HCStatus] [varchar](max) NULL,
	[ShipQty_by_Seq] [int] NULL,
	[PackingQty_bySeq] [int] NULL,
	[CTNQty_bySeq] [int] NULL,
	[OrderQty_bySeq] [int] NULL,
	[FOC_Bal_Qty] [int] NULL,
	[Pullout_ID] [varchar](max) NULL
);

