CREATE TABLE [dbo].[P_EstShippingReport] (
    [BuyerDelivery]       DATE            NULL,
    [Brand]               VARCHAR (8)     NULL,
    [SPNO]                VARCHAR (13)    NULL,
    [Category]            VARCHAR (8)     NULL,
    [Seq]                 VARCHAR (2)     NULL,
    [PackingNo]           VARCHAR (MAX)   NULL,
    [PackingStatus]       VARCHAR (MAX)   NULL,
    [GBNo]                VARCHAR (MAX)   NULL,
    [PulloutDate]         VARCHAR (MAX)   NULL,
    [Order_TtlQty]        INT             NULL,
    [SO_No]               VARCHAR (16)    NULL,
    [SO_CfmDate]          DATE            NULL,
    [CutOffDate]          DATETIME        NULL,
    [ShipPlanID]          VARCHAR (13)    NULL,
    [M]                   VARCHAR (8)     NULL,
    [Factory]             VARCHAR (8)     NULL,
    [Destination]         VARCHAR (30)    NULL,
    [Price]               NUMERIC (16, 3) NULL,
    [GW]                  NUMERIC (8, 3)  NULL,
    [CBM]                 NUMERIC (13, 4) NULL,
    [ShipMode]            VARCHAR (10)    NULL,
    [Handle]              VARCHAR (80)    NULL,
    [LocalMR]             VARCHAR (80)    NULL,
    [SP_SEQ]              VARCHAR (15)    NULL,
    [If_Partial]          VARCHAR (1)     NULL,
    [CartonQtyAtCLog]     INT             NULL,
    [SP_Prod_Output_Qty]  INT             NULL,
    [OrderType]           VARCHAR (20)    NULL,
    [BuyBack]             VARCHAR (1)     NULL,
    [LoadingType]         VARCHAR (MAX)   NULL,
    [Est_PODD]            DATE            NULL,
    [Origin]              VARCHAR (2)     NULL,
    [Outstanding_Reason2] NVARCHAR (800)  NULL,
    [Outstanding_Remark]  NVARCHAR (MAX)  NULL,
    [ReturnedQty_bySeq]   INT             NULL,
    [HC#]                 VARCHAR (MAX)   NULL,
    [HCStatus]            VARCHAR (MAX)   NULL,
    [ShipQty_by_Seq]      INT             NULL,
    [PackingQty_bySeq]    INT             NULL,
    [CTNQty_bySeq]        INT             NULL,
    [OrderQty_bySeq]      INT             NULL,
    [FOC_Bal_Qty]         INT             NULL,
    [Pullout_ID]          VARCHAR (MAX)   NULL
);

