CREATE TABLE [dbo].[P_LoadingProductionOutput] (
    [MDivisionID]            VARCHAR (8)     NULL,
    [FtyZone]                VARCHAR (8)     NULL,
    [FactoryID]              VARCHAR (8)     NOT NULL,
    [BuyerDelivery]          DATE            NULL,
    [SciDelivery]            DATE            NULL,
    [SCIKey]                 NVARCHAR (4000) NULL,
    [SCIKeyHalf]             NVARCHAR (4000) NULL,
    [BuyerKey]               NVARCHAR (4000) NULL,
    [BuyerKeyHalf]           NVARCHAR (4000) NULL,
    [SPNO]                   VARCHAR (24)    NULL,
    [Category]               VARCHAR (8)     NULL,
    [Cancelled]              VARCHAR (1)     NOT NULL,
    [IsCancelNeedProduction] VARCHAR (1)     NOT NULL,
    [PartialShipment]        VARCHAR (1)     NULL,
    [LastBuyerDelivery]      DATE            NULL,
    [StyleID]                VARCHAR (15)    NULL,
    [SeasonID]               VARCHAR (10)    NULL,
    [CustPONO]               VARCHAR (30)    NULL,
    [BrandID]                VARCHAR (8)     NULL,
    [CPU]                    NUMERIC (8, 3)  NULL,
    [Qty]                    INT             NULL,
    [FOCQty]                 INT             NULL,
    [PulloutQty]             INT             NULL,
    [OrderShortageCPU]       NUMERIC (23, 4) NULL,
    [TotalCPU]               NUMERIC (23, 4) NULL,
    [SewingOutput]           NUMERIC (38, 6) NULL,
    [SewingOutputCPU]        NUMERIC (38, 6) NULL,
    [BalanceQty]             NUMERIC (38, 6) NULL,
    [BalanceCPU]             NUMERIC (38, 6) NULL,
    [BalanceCPUIrregular]    NUMERIC (38, 6) NULL,
    [SewLine]                VARCHAR (60)    NULL,
    [Dest]                   VARCHAR (2)     NULL,
    [OrderTypeID]            VARCHAR (20)    NULL,
    [ProgramID]              VARCHAR (12)    NULL,
    [CdCodeID]               VARCHAR (6)     NULL,
    [ProductionFamilyID]     VARCHAR (20)    NULL,
    [FtyGroup]               VARCHAR (8)     NULL,
    [PulloutComplete]        VARCHAR (2)     NOT NULL,
    [SewInLine]              DATE            NULL,
    [SewOffLine]             DATE            NULL,
    [TransFtyZone]           VARCHAR (8)     NULL
);

