CREATE TABLE [dbo].[P_MISCPurchaseOrderList]
(
	[PurchaseFrom]		varchar(6)		NOT NULL DEFAULT (''), 
	[MDivisionID]		varchar(8)		NOT NULL DEFAULT (''), 
	[FactoryID]			varchar(8)		NOT NULL DEFAULT (''), 
	[PONo]				varchar(13)		NOT NULL DEFAULT (''), 
	[PRConfirmedDate]	datetime		NULL, 
	[CreateDate]		date			NULL, 
	[DeliveryDate]		date			NULL, 
	[Type]				varchar(20)		NOT NULL DEFAULT (''), 
	[Supplier]			nvarchar(30)	NOT NULL DEFAULT (''), 
	[Status]			varchar(15)		NOT NULL DEFAULT (''), 
	[ReqNo]				varchar(13)		NOT NULL DEFAULT (''), 
	[PRDate]			date			NULL, 
	[Code]				varchar(23)		NOT NULL DEFAULT (''), 
	[Description]		nvarchar(1000)	NOT NULL DEFAULT (''), 
	[POQty]				decimal(8,2)	NOT NULL DEFAULT ((0)), 
	[UnitID]			varchar(8)		NOT NULL DEFAULT (''), 
	[CurrencyID]		varchar(3)		NOT NULL DEFAULT (''), 
	[UnitPrice]			numeric(16,4)	NOT NULL DEFAULT ((0)), 
	[UnitPrice_USD]		numeric(16,4)	NOT NULL DEFAULT ((0)), 
	[POAmount]			numeric(25,6)	NOT NULL DEFAULT ((0)), 
	[POAmount_USD]		numeric(16,4)	NOT NULL DEFAULT ((0)), 
	[AccInQty]			decimal(8,2)	NOT NULL DEFAULT ((0)), 
	[TPEPO]				varchar(13)		NOT NULL DEFAULT (''), 
	[TPEQty]			numeric(8,2)	NOT NULL DEFAULT ((0)), 
	[TPECurrencyID]		varchar(3)		NOT NULL DEFAULT (''), 
	[TPEPrice]			numeric(16,4)	NOT NULL DEFAULT ((0)), 
	[TPEAmount]			numeric(25,6)	NOT NULL DEFAULT ((0)), 
	[ApQty]				decimal(8,2)	NOT NULL DEFAULT ((0)), 
	[APAmount]			numeric(23,6)	NOT NULL DEFAULT ((0)), 
	[RentalDay]			int				NOT NULL DEFAULT ((0)), 
	[IncomingDate]		date			NULL , 
	[APApprovedDate]	date			NULL , 
	[Invoice]			varchar(max)	NOT NULL DEFAULT (''), 
	[RequestReason]		nvarchar(300)	NOT NULL DEFAULT (''), 
	[ProjectItem]		varchar(1)		NOT NULL DEFAULT (''), 
	[Project]			varchar(211)	NOT NULL DEFAULT (''), 
	[DepartmentID]		varchar(8)		NOT NULL DEFAULT (''), 
	[AccountID]			varchar(8)		NOT NULL DEFAULT (''), 
	[AccountName]		nvarchar(40)	NOT NULL DEFAULT (''), 
	[AccountCategory]	nvarchar(50)	NOT NULL DEFAULT (''), 
	[Budget]			varchar(100)	NOT NULL DEFAULT (''), 
	[InternalRemarks]	nvarchar(max)	NOT NULL DEFAULT (''), 
	[APID]				varchar(300)	NOT NULL DEFAULT (''), 
    CONSTRAINT [PK_P_MISCPurchaseOrderList] PRIMARY KEY ([PONo],[Code],[ReqNo]), 
)
