CREATE TABLE [dbo].[P_OustandingPO_Original](
	[FactoryID] [varchar](8) NOT NULL,
	[OrderID] [varchar](13) NOT NULL,
	[CustPONo] [varchar](30) NOT NULL,
	[StyleID] [varchar](15) NOT NULL,
	[BrandID] [varchar](8) NOT NULL,
	[BuyerDelivery] [date] NULL,
	[Seq] [varchar](2) NOT NULL,
	[ShipModeID] [varchar](10) NOT NULL,
	[Category] [varchar](10) NOT NULL,
	[PartialShipment] [varchar](1) NOT NULL,
	[Junk] [varchar](1) NOT NULL,
	[OrderQty] [int] NOT NULL,
	[PackingCtn] [int] NOT NULL,
	[PackingQty] [int] NOT NULL,
	[ClogRcvCtn] [int] NOT NULL,
	[ClogRcvQty] [varchar](10) NOT NULL,
	[LastCMPOutputDate] [date] NULL,
	[CMPQty] [varchar](10) NOT NULL,
	[LastDQSOutputDate] [date] NULL,
	[DQSQty] [varchar](10) NOT NULL,
	[OSTPackingQty] [varchar](10) NOT NULL,
	[OSTCMPQty] [varchar](10) NOT NULL,
	[OSTDQSQty] [varchar](10) NOT NULL,
	[OSTClogQty] [varchar](10) NOT NULL,
	[OSTClogCtn] [int] NOT NULL,
	[PulloutComplete] [varchar](1) NOT NULL,
	[Dest] [varchar](30) NULL
) ON [PRIMARY]