CREATE TABLE [dbo].[P_QA_R31_Original](
	[Stage] [varchar](20) NULL,
	[InspResult] [varchar](10) NULL,
	[NotYetInspCtn#] [varchar](max) NULL,
	[NotYetInspCtn] [int] NULL,
	[NotYetInspQty] [int] NULL,
	[FailCtn#] [varchar](5000) NULL,
	[FailCtn] [int] NULL,
	[FailQty] [int] NULL,
	[MDivisionID] [varchar](8) NULL,
	[FactoryID] [varchar](8) NOT NULL,
	[BuyerDelivery] [date] NULL,
	[BrandID] [varchar](8) NULL,
	[OrderID] [varchar](13) NULL,
	[Category] [varchar](15) NULL,
	[OrderTypeID] [varchar](20) NULL,
	[CustPoNo] [varchar](30) NULL,
	[StyleID] [varchar](15) NULL,
	[StyleName] [nvarchar](50) NULL,
	[SeasonID] [varchar](10) NULL,
	[Dest] [varchar](30) NULL,
	[Customize1] [varchar](30) NULL,
	[CustCDID] [varchar](16) NULL,
	[Seq] [varchar](6) NULL,
	[ShipModeID] [varchar](10) NULL,
	[ColorWay] [varchar](200) NULL,
	[SewLine] [varchar](60) NULL,
	[TtlCtn] [varchar](15) NULL,
	[StaggeredCtn] [varchar](15) NULL,
	[ClogCtn] [varchar](15) NULL,
	[ClogCtn%] [varchar](15) NULL,
	[LastCartonReceivedDate] [date] NULL,
	[CFAFinalInspectDate] [date] NULL,
	[CFA3rdInspectDate] [date] NULL,
	[CFARemark] [nvarchar](500) NULL,
	[Ukey] [bigint] NOT NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]