CREATE TABLE [dbo].[P_QA_R31] (
    [Stage]                  VARCHAR (20)   NULL,
    [InspResult]             VARCHAR (10)   NULL,
    [NotYetInspCtn#]         VARCHAR (MAX)  NULL,
    [NotYetInspCtn]          INT            NULL,
    [NotYetInspQty]          INT            NULL,
    [FailCtn#]               VARCHAR (5000) NULL,
    [FailCtn]                INT            NULL,
    [FailQty]                INT            NULL,
    [MDivisionID]            VARCHAR (8)    NULL,
    [FactoryID]              VARCHAR (8)    NULL,
    [BuyerDelivery]          DATE           NULL,
    [BrandID]                VARCHAR (8)    NULL,
    [OrderID]                VARCHAR (13)   NULL,
    [Category]               VARCHAR (15)   NULL,
    [OrderTypeID]            VARCHAR (20)   NULL,
    [CustPoNo]               VARCHAR (30)   NULL,
    [StyleID]                VARCHAR (15)   NULL,
    [StyleName]              NVARCHAR (50)  NULL,
    [SeasonID]               VARCHAR (10)   NULL,
    [Dest]                   VARCHAR (30)   NULL,
    [Customize1]             VARCHAR (30)   NULL,
    [CustCDID]               VARCHAR (16)   NULL,
    [Seq]                    VARCHAR (6)    NULL,
    [ShipModeID]             VARCHAR (10)   NULL,
    [ColorWay]               VARCHAR (200)  NULL,
    [SewLine]                VARCHAR (60)   NULL,
    [TtlCtn]                 VARCHAR (15)   NULL,
    [StaggeredCtn]           VARCHAR (15)   NULL,
    [ClogCtn]                VARCHAR (15)   NULL,
    [ClogCtn%]               VARCHAR (15)   NULL,
    [LastCartonReceivedDate] DATE           NULL,
    [CFAFinalInspectDate]    DATE           NULL,
    [CFA3rdInspectDate]      DATE           NULL,
    [CFARemark]              NVARCHAR (500) NULL
);

