CREATE TABLE [dbo].[P_QA_P09_Original](
	[WK#] [varchar](13) NULL,
	[FactoryID] [varchar](8) NOT NULL,
	[Invoice#] [varchar](200) NULL,
	[ATA] [date] NULL,
	[ETA] [date] NULL,
	[Season] [varchar](10) NULL,
	[SP#] [varchar](13) NULL,
	[Seq#] [varchar](10) NULL,
	[Brand] [varchar](8) NULL,
	[Supp] [varchar](6) NULL,
	[Supp Name] [varchar](12) NULL,
	[Ref#] [varchar](20) NULL,
	[Color] [nvarchar](150) NULL,
	[Qty] [numeric](12, 2) NULL,
	[Inspection Report_Fty Received Date] [date] NULL,
	[Inspection Report_Supp Sent Date] [date] NULL,
	[Test Report_Fty Received Date] [date] NULL,
	[Test Report_ Check Clima] [bit] NULL,
	[Test Report_Supp Sent Date] [date] NULL,
	[Continuity Card_Fty Received Date] [date] NULL,
	[Continuity Card_Supp Sent Date] [date] NULL,
	[Continuity Card_AWB#] [varchar](30) NULL,
	[1st Bulk Dyelot_Fty Received Date] [date] NULL,
	[1st Bulk Dyelot_Supp Sent Date] [varchar](100) NULL,
	[T2 Inspected Yards] [numeric](10, 2) NULL,
	[T2 Defect Points] [numeric](5, 0) NULL,
	[Grade] [varchar](1) NULL,
	[T1 Inspected Yards] [numeric](10, 2) NULL,
	[T1 Defect Points] [numeric](6, 0) NULL,
	[Fabric with clima] [bit] NULL,
	[Ukey] [bigint] NOT NULL
) ON [PRIMARY]