CREATE TABLE [dbo].[P_QA_R06_Original](
	[SuppID] [varchar](15) NOT NULL,
	[Refno] [varchar](50) NOT NULL,
	[SupplierName] [varchar](50) NULL,
	[BrandID] [varchar](500) NULL,
	[StockQty] [numeric](9, 2) NULL,
	[TotalInspYds] [int] NULL,
	[TotalPoCnt] [int] NULL,
	[TotalDyelot] [int] NULL,
	[TotalDyelotAccepted] [int] NULL,
	[InspReport] [numeric](9, 2) NULL,
	[TestReport] [numeric](9, 2) NULL,
	[ContinuityCard] [numeric](9, 2) NULL,
	[BulkDyelot] [numeric](9, 2) NULL,
	[TotalPoint] [int] NULL,
	[TotalRoll] [int] NULL,
	[GradeARoll] [int] NULL,
	[GradeBRoll] [int] NULL,
	[GradeCRoll] [int] NULL,
	[Inspected] [numeric](9, 2) NULL,
	[Yds] [numeric](9, 2) NULL,
	[FabricPercent] [numeric](9, 2) NULL,
	[FabricLevel] [varchar](1) NULL,
	[Point] [varchar](150) NULL,
	[SHRINKAGEyards] [numeric](9, 2) NULL,
	[SHRINKAGEPercent] [numeric](9, 2) NULL,
	[SHINGKAGELevel] [varchar](1) NULL,
	[MIGRATIONyards] [numeric](9, 2) NULL,
	[MIGRATIONPercent] [numeric](9, 2) NULL,
	[MIGRATIONLevel] [varchar](1) NULL,
	[SHADINGyards] [numeric](9, 2) NULL,
	[SHADINGPercent] [numeric](9, 2) NULL,
	[SHADINGLevel] [varchar](1) NULL,
	[ActualYds] [numeric](9, 2) NULL,
	[LACKINGYARDAGEPercent] [numeric](9, 2) NULL,
	[LACKINGYARDAGELevel] [varchar](1) NULL,
	[SHORTWIDTH] [numeric](9, 2) NULL,
	[SHORTWidthPercent] [numeric](9, 2) NULL,
	[SHORTWIDTHLevel] [varchar](1) NULL,
	[TotalDefectRate] [numeric](9, 2) NULL,
	[TotalLevel] [varchar](1) NULL,
	[WhseArrival] [varchar](15) NOT NULL,
	[FactoryID] [varchar](30) NOT NULL,
	[Clima] [bit] NULL,
	[POID] [varchar](13) NOT NULL
) ON [PRIMARY]