CREATE TABLE [dbo].[P_QA_P09] (
    [WK#]                                 VARCHAR (13)    NULL,
    [FactoryID]                           VARCHAR (8)     NULL,
    [Invoice#]                            VARCHAR (200)   NULL,
    [ATA]                                 DATE            NULL,
    [ETA]                                 DATE            NULL,
    [Season]                              VARCHAR (10)    NULL,
    [SP#]                                 VARCHAR (13)    NULL,
    [Seq#]                                VARCHAR (10)    NULL,
    [Brand]                               VARCHAR (8)     NULL,
    [Supp]                                VARCHAR (6)     NULL,
    [Supp Name]                           VARCHAR (12)    NULL,
    [Ref#]                                VARCHAR (20)    NULL,
    [Color]                               NVARCHAR (150)  NULL,
    [Qty]                                 NUMERIC (12, 2) NULL,
    [Inspection Report_Fty Received Date] DATE            NULL,
    [Inspection Report_Supp Sent Date]    DATE            NULL,
    [Test Report_Fty Received Date]       DATE            NULL,
    [Test Report_ Check Clima]            BIT             NULL,
    [Test Report_Supp Sent Date]          DATE            NULL,
    [Continuity Card_Fty Received Date]   DATE            NULL,
    [Continuity Card_Supp Sent Date]      DATE            NULL,
    [Continuity Card_AWB#]                VARCHAR (30)    NULL,
    [1st Bulk Dyelot_Fty Received Date]   DATE            NULL,
    [1st Bulk Dyelot_Supp Sent Date]      VARCHAR (100)   NULL,
    [T2 Inspected Yards]                  NUMERIC (10, 2) NULL,
    [T2 Defect Points]                    NUMERIC (5)     NULL,
    [Grade]                               VARCHAR (1)     NULL,
    [T1 Inspected Yards]                  NUMERIC (10, 2) NULL,
    [T1 Defect Points]                    NUMERIC (6)     NULL,
    [Fabric with clima]                   BIT             NULL
);



