CREATE TABLE [dbo].[P_SDPOrderDetail] (
    [CountryID]          VARCHAR (2)    DEFAULT ('') NOT NULL,
    [KPICode]            VARCHAR (8)    DEFAULT ('') NOT NULL,
    [FactoryID]          VARCHAR (8)    DEFAULT ('') NOT NULL,
    [OrderID]            VARCHAR (13)   NULL,
    [StyleID]            VARCHAR (15)   NULL,
    [Seq]                VARCHAR (2)    DEFAULT ('') NOT NULL,
    [BrandID]            VARCHAR (8)    DEFAULT ('') NOT NULL,
    [BuyerDelivery]      DATE           NULL,
    [FtyKPI]             DATE           NULL,
    [Extension]          VARCHAR (10)   DEFAULT ('') NOT NULL,
    [DeliveryByShipMode] VARCHAR (10)   DEFAULT ('') NOT NULL,
    [OrderQty]           INT            DEFAULT ((0)) NOT NULL,
    [OnTimeQty]          INT            DEFAULT ((0)) NOT NULL,
    [FailQty]            INT            DEFAULT ((0)) NOT NULL,
    [PullOutDate]        DATE           NULL,
    [ShipMode]           VARCHAR (10)   DEFAULT ('') NOT NULL,
    [P]                  INT            DEFAULT ((0)) NOT NULL,
    [GMTComplete]        VARCHAR (1)    DEFAULT ('') NOT NULL,
    [ReasonID]           VARCHAR (5)    DEFAULT ('') NOT NULL,
    [ReasonName]         NVARCHAR (500) DEFAULT ('') NOT NULL,
    [SewLastDate]        DATE           NULL,
    [CTNLastReceiveDate] DATETIME       NULL,
    [ReasonRemark]       NVARCHAR (60)  DEFAULT ('') NOT NULL,
    [MR]                 VARCHAR (100)  DEFAULT ('') NOT NULL,
    [SMR]                VARCHAR (100)  DEFAULT ('') NOT NULL,
    [POHandle]           VARCHAR (100)  DEFAULT ('') NULL,
    [POSMR]              VARCHAR (100)  DEFAULT ('') NOT NULL,
    [OrderTypeID]        VARCHAR (20)   DEFAULT ('') NOT NULL,
    [isDevSample]        VARCHAR (1)    DEFAULT ('') NOT NULL,
    [SewouptQty]         INT            DEFAULT ((0)) NOT NULL,
    [FOC]                INT            DEFAULT ((0)) NOT NULL,
    [Order_QtyShipCount] VARCHAR (1)    DEFAULT ('') NOT NULL,
    [Alias]              VARCHAR (30)   DEFAULT ('') NOT NULL,
    [OutstandingReason]  VARCHAR (5)    DEFAULT ('') NOT NULL,
    [OutstandingRemark]  NVARCHAR (60)  DEFAULT ('') NOT NULL,
    [OSTClogCarton]      INT            DEFAULT ((0)) NOT NULL
);

