CREATE TABLE [dbo].[P_SewingLineSchedule] (
    [APSNo]                    INT             NULL,
    [SewingLineID]             VARCHAR (2)     NULL,
    [SewingDay]                DATE            NULL,
    [SewingStartTime]          DATETIME        NULL,
    [SewingEndTime]            DATETIME        NULL,
    [MDivisionID]              VARCHAR (8)     NULL,
    [FactoryID]                VARCHAR (8)     NULL,
    [PO]                       NVARCHAR (MAX)  NULL,
    [POCount]                  BIGINT          NULL,
    [SP]                       NVARCHAR (MAX)  NULL,
    [SPCount]                  INT             NULL,
    [EarliestSCIdelivery]      DATE            NULL,
    [LatestSCIdelivery]        DATE            NULL,
    [EarliestBuyerdelivery]    DATE            NULL,
    [LatestBuyerdelivery]      DATE            NULL,
    [Category]                 NVARCHAR (MAX)  NULL,
    [Colorway]                 NVARCHAR (MAX)  NULL,
    [ColorwayCount]            BIGINT          NULL,
    [CDCode]                   NVARCHAR (MAX)  NULL,
    [ProductionFamilyID]       NVARCHAR (MAX)  NULL,
    [Style]                    NVARCHAR (MAX)  NULL,
    [StyleCount]               BIGINT          NULL,
    [OrderQty]                 INT             NULL,
    [AlloQty]                  INT             NULL,
    [StardardOutputPerDay]     FLOAT (53)      NULL,
    [CPU]                      FLOAT (53)      NULL,
    [WorkHourPerDay]           FLOAT (53)      NULL,
    [StardardOutputPerHour]    FLOAT (53)      NULL,
    [Efficienycy]              NUMERIC (10, 2) NULL,
    [ScheduleEfficiency]       NUMERIC (11, 2) NULL,
    [LineEfficiency]           NUMERIC (11, 2) NULL,
    [LearningCurve]            NUMERIC (17, 2) NULL,
    [SewingInline]             DATETIME        NULL,
    [SewingOffline]            DATETIME        NULL,
    [PFRemark]                 VARCHAR (1)     NULL,
    [MTLComplete]              VARCHAR (1)     NULL,
    [KPILETA]                  DATE            NULL,
    [MTLETA]                   DATE            NULL,
    [ArtworkType]              NVARCHAR (MAX)  NULL,
    [InspectionDate]           DATE            NULL,
    [Remarks]                  NVARCHAR (MAX)  NULL,
    [CuttingOutput]            NUMERIC (38, 2) NULL,
    [SewingOutput]             INT             NULL,
    [ScannedQty]               INT             NULL,
    [ClogQty]                  INT             NULL,
    [Sewer]                    INT             NULL,
    [SewingCPU]                NUMERIC (10, 2) NULL,
    [BrandID]                  NVARCHAR (MAX)  NULL,
    [Orig_WorkHourPerDay]      FLOAT (53)      NULL,
    [New_SwitchTime]           FLOAT (53)      NULL,
    [FirststCuttingOutputDate] DATE            NULL,
    [CDCodeNew] VARCHAR(5) NULL, 
    [ProductType] NVARCHAR(500) NULL, 
    [FabricType] NVARCHAR(500) NULL, 
    [Lining] VARCHAR(20) NULL, 
    [Gender] VARCHAR(10) NULL, 
    [Construction] NVARCHAR(50) NULL
);





