CREATE TABLE [dbo].[P_SewingLineSchedule_Original](
	[APSNo] [int] NULL,
	[SewingLineID] [varchar](5) NULL,
	[SewingDay] [date] NULL,
	[SewingStartTime] [datetime] NULL,
	[SewingEndTime] [datetime] NULL,
	[MDivisionID] [varchar](8) NULL,
	[FactoryID] [varchar](8) NULL,
	[PO] [nvarchar](max) NULL,
	[POCount] [bigint] NULL,
	[SP] [nvarchar](max) NULL,
	[SPCount] [int] NULL,
	[EarliestSCIdelivery] [date] NULL,
	[LatestSCIdelivery] [date] NULL,
	[EarliestBuyerdelivery] [date] NULL,
	[LatestBuyerdelivery] [date] NULL,
	[Category] [nvarchar](max) NULL,
	[Colorway] [nvarchar](max) NULL,
	[ColorwayCount] [bigint] NULL,
	[CDCode] [nvarchar](max) NULL,
	[ProductionFamilyID] [nvarchar](max) NULL,
	[Style] [nvarchar](max) NULL,
	[StyleCount] [bigint] NULL,
	[OrderQty] [int] NULL,
	[AlloQty] [int] NULL,
	[StardardOutputPerDay] [float] NULL,
	[CPU] [float] NULL,
	[WorkHourPerDay] [float] NULL,
	[StardardOutputPerHour] [float] NULL,
	[Efficienycy] [numeric](10, 2) NULL,
	[ScheduleEfficiency] [numeric](11, 2) NULL,
	[LineEfficiency] [numeric](11, 2) NULL,
	[LearningCurve] [numeric](17, 2) NULL,
	[SewingInline] [datetime] NULL,
	[SewingOffline] [datetime] NULL,
	[PFRemark] [varchar](1) NULL,
	[MTLComplete] [varchar](1) NULL,
	[KPILETA] [date] NULL,
	[MTLETA] [date] NULL,
	[ArtworkType] [nvarchar](max) NULL,
	[InspectionDate] [date] NULL,
	[Remarks] [nvarchar](max) NULL,
	[CuttingOutput] [numeric](38, 2) NULL,
	[SewingOutput] [int] NULL,
	[ScannedQty] [int] NULL,
	[ClogQty] [int] NULL,
	[Sewer] [int] NULL,
	[SewingCPU] [numeric](10, 2) NULL,
	[BrandID] [nvarchar](max) NULL,
	[Orig_WorkHourPerDay] [float] NULL,
	[New_SwitchTime] [float] NULL,
	[FirststCuttingOutputDate] [date] NULL,
	[CDCodeNew] [varchar](max) NULL,
	[ProductType] [nvarchar](max) NULL,
	[FabricType] [nvarchar](max) NULL,
	[Lining] [varchar](max) NULL,
	[Gender] [varchar](max) NULL,
	[Construction] [nvarchar](max) NULL,
	[TTL_PRINTING (PCS)] [numeric](38, 6) NULL,
	[TTL_PRINTING PPU (PPU)] [numeric](38, 6) NULL,
	[SubCon] [nvarchar](max) NULL,
	[Subcon Qty] [int] NULL,
	[Std Qty for printing] [int] NULL,
	[StyleName] [nvarchar](max) NULL,
	[StdQtyEMB] [varchar](50) NULL,
	[EMBStitch] [varchar](20) NULL,
	[EMBStitchCnt] [int] NULL,
	[TtlQtyEMB] [int] NULL,
	[PrintPcs] [int] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[P_SewingLineSchedule_Original] ADD  CONSTRAINT [DF_P_SewingLineSchedule_Original_StyleName]  DEFAULT ('') FOR [StyleName]
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'款式名稱' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'P_SewingLineSchedule_Original', @level2type=N'COLUMN',@level2name=N'StyleName'
GO
