CREATE TABLE [dbo].[P_SewingLineScheduleBySP]
(
	[ID] BIGINT NOT NULL, 
    [SewingLineID] VARCHAR(5) NOT NULL CONSTRAINT [CONSTRAINT_P_SewingLineScheduleBySP_SewingLineID] DEFAULT (''), 
    [MDivisionID] VARCHAR(8) NOT NULL CONSTRAINT [CONSTRAINT_P_SewingLineScheduleBySP_MDivisionID] DEFAULT (''), 
    [FactoryID] VARCHAR(8) NOT NULL CONSTRAINT [CONSTRAINT_P_SewingLineScheduleBySP_FactoryID] DEFAULT (''), 
    [SPNo] VARCHAR(13) NOT NULL CONSTRAINT [CONSTRAINT_P_SewingLineScheduleBySP_SPNo] DEFAULT (''), 
    [CustPONo] VARCHAR(30) NOT NULL CONSTRAINT [CONSTRAINT_P_SewingLineScheduleBySP_CustPONo] DEFAULT (''), 
    [Category] VARCHAR NOT NULL CONSTRAINT [CONSTRAINT_P_SewingLineScheduleBySP_Category] DEFAULT (''), 
    [ComboType] VARCHAR NOT NULL CONSTRAINT [CONSTRAINT_P_SewingLineScheduleBySP_ComboType] DEFAULT (''), 
    [SwitchToWorkorder] VARCHAR(12) NOT NULL CONSTRAINT [CONSTRAINT_P_SewingLineScheduleBySP_SwitchToWorkorder] DEFAULT (''), 
    [Colorway] NVARCHAR(MAX) NOT NULL CONSTRAINT [CONSTRAINT_P_SewingLineScheduleBySP_Colorway] DEFAULT (''), 
    [SeasonID] VARCHAR(10) NOT NULL CONSTRAINT [CONSTRAINT_P_SewingLineScheduleBySP_SeasonID] DEFAULT (''), 
    [CDCodeNew] VARCHAR(5) NOT NULL CONSTRAINT [CONSTRAINT_P_SewingLineScheduleBySP_CDCodeNew] DEFAULT (''), 
    [ProductType] NVARCHAR(100) NOT NULL CONSTRAINT [CONSTRAINT_P_SewingLineScheduleBySP_ProductType] DEFAULT (''), 
    [MatchFabric] VARCHAR NOT NULL CONSTRAINT [CONSTRAINT_P_SewingLineScheduleBySP_MatchFabric] DEFAULT (''), 
    [FabricType] NVARCHAR(100) NOT NULL CONSTRAINT [CONSTRAINT_P_SewingLineScheduleBySP_FabricType] DEFAULT (''), 
    [Lining] VARCHAR(20) NOT NULL CONSTRAINT [CONSTRAINT_P_SewingLineScheduleBySP_Lining] DEFAULT (''), 
    [Gender] VARCHAR(10) NOT NULL CONSTRAINT [CONSTRAINT_P_SewingLineScheduleBySP_Gender] DEFAULT (''), 
    [Construction] NVARCHAR(100) NOT NULL CONSTRAINT [CONSTRAINT_P_SewingLineScheduleBySP_Construction] DEFAULT (''), 
    [StyleID] VARCHAR(15) NOT NULL CONSTRAINT [CONSTRAINT_P_SewingLineScheduleBySP_StyleID] DEFAULT (''), 
    [OrderQty] INT NOT NULL CONSTRAINT [CONSTRAINT_P_SewingLineScheduleBySP_OrderQty] DEFAULT (0), 
    [AlloQty] INT NOT NULL CONSTRAINT [CONSTRAINT_P_SewingLineScheduleBySP_AlloQty] DEFAULT (0), 
    [CutQty] NUMERIC(11, 2) NOT NULL CONSTRAINT [CONSTRAINT_P_SewingLineScheduleBySP_CutQty] DEFAULT (0), 
    [SewingQty] INT NOT NULL CONSTRAINT [CONSTRAINT_P_SewingLineScheduleBySP_SewingQty] DEFAULT (0), 
    [ClogQty] INT NOT NULL CONSTRAINT [CONSTRAINT_P_SewingLineScheduleBySP_ClogQty] DEFAULT (0), 
    [FirstCuttingOutputDate] DATE NULL, 
    [InspectionDate] NVARCHAR(100) NOT NULL CONSTRAINT [CONSTRAINT_P_SewingLineScheduleBySP_InspectionDate] DEFAULT (''), 
    [TotalStandardOutput] NUMERIC(11, 6) NOT NULL CONSTRAINT [CONSTRAINT_P_SewingLineScheduleBySP_TotalStandardOutput] DEFAULT (0), 
    [WorkHour] NUMERIC(8, 6) NOT NULL CONSTRAINT [CONSTRAINT_P_SewingLineScheduleBySP_WorkHour] DEFAULT (0), 
    [StandardOutputPerHour] INT NOT NULL CONSTRAINT [CONSTRAINT_P_SewingLineScheduleBySP_StandardOutputPerHour] DEFAULT (0), 
    [Efficiency] NUMERIC(10, 2) NOT NULL CONSTRAINT [CONSTRAINT_P_SewingLineScheduleBySP_Efficiency] DEFAULT (0), 
    [KPILETA] DATE NULL, 
    [PFRemark] NVARCHAR(MAX) NOT NULL CONSTRAINT [CONSTRAINT_P_SewingLineScheduleBySP_PFRemark] DEFAULT (''), 
    [ActMTLETA] DATE NULL, 
    [MTLExport] VARCHAR(2) NOT NULL CONSTRAINT [CONSTRAINT_P_SewingLineScheduleBySP_MTLExport] DEFAULT (''), 
    [CutInLine] DATE NULL, 
    [Inline] DATETIME NULL, 
    [Offline] DATETIME NULL, 
    [SCIDelivery] DATE NULL, 
    [BuyerDelivery] DATE NULL, 
    [CRDDate] DATE NULL, 
    [CPU] NUMERIC(8, 3) NOT NULL CONSTRAINT [CONSTRAINT_P_SewingLineScheduleBySP_CPU] DEFAULT (0), 
    [SewingCPU] NUMERIC(12, 5) NOT NULL CONSTRAINT [CONSTRAINT_P_SewingLineScheduleBySP_SewingCPU] DEFAULT (0), 
    [VASSHAS] VARCHAR NOT NULL CONSTRAINT [CONSTRAINT_P_SewingLineScheduleBySP_VASSHAS] DEFAULT (''), 
    [ShipModeList] VARCHAR(30) NOT NULL CONSTRAINT [CONSTRAINT_P_SewingLineScheduleBySP_ShipModeList] DEFAULT (''), 
    [Destination] VARCHAR(30) NOT NULL CONSTRAINT [CONSTRAINT_P_SewingLineScheduleBySP_Destination] DEFAULT (''), 
    [Artwork] NVARCHAR(MAX) NOT NULL CONSTRAINT [CONSTRAINT_P_SewingLineScheduleBySP_Artwork] DEFAULT (''), 
    [Remarks] NVARCHAR(MAX) NOT NULL CONSTRAINT [CONSTRAINT_P_SewingLineScheduleBySP_Remarks] DEFAULT (''), 
    [TTL_PRINTING_PCS] NUMERIC(38, 6) NOT NULL CONSTRAINT [CONSTRAINT_P_SewingLineScheduleBySP_TTL_PRINTING_PCS] DEFAULT (0), 
    [TTL_PRINTING_PPU_PPU] NUMERIC(38, 6) NOT NULL CONSTRAINT [CONSTRAINT_P_SewingLineScheduleBySP_TTL_PRINTING_PPU_PPU] DEFAULT (0), 
    [SubCon] NVARCHAR(20) NOT NULL CONSTRAINT [CONSTRAINT_P_SewingLineScheduleBySP_SubCon] DEFAULT (''), 
    CONSTRAINT [PK_P_SewingLineScheduleBySP] PRIMARY KEY ([ID])
)