CREATE TABLE [dbo].[P_SewingDailyOutput_Original](
	[Ukey] [bigint] NOT NULL,
	[MDivisionID] [varchar](20) NOT NULL,
	[FactoryID] [varchar](20) NULL,
	[ComboType] [varchar](1) NOT NULL,
	[Category] [varchar](20) NULL,
	[CountryID] [varchar](20) NULL,
	[OutputDate] [date] NULL,
	[SewingLineID] [varchar](10) NULL,
	[Shift] [varchar](30) NULL,
	[SubconOutFty] [varchar](15) NULL,
	[SubConOutContractNumber] [varchar](50) NULL,
	[Team] [varchar](10) NULL,
	[OrderID] [varchar](13) NULL,
	[Article] [varchar](8) NULL,
	[SizeCode] [varchar](8) NULL,
	[CustPONo] [varchar](30) NULL,
	[BuyerDelivery] [date] NULL,
	[OrderQty] [int] NULL,
	[BrandID] [varchar](20) NULL,
	[OrderCategory] [varchar](20) NULL,
	[ProgramID] [varchar](20) NULL,
	[OrderTypeID] [varchar](20) NULL,
	[DevSample] [varchar](5) NULL,
	[CPURate] [numeric](15, 1) NULL,
	[StyleID] [varchar](20) NULL,
	[Season] [varchar](10) NULL,
	[CdCodeID] [varchar](15) NULL,
	[ActualManpower] [numeric](12, 1) NULL,
	[NoOfHours] [numeric](10, 4) NULL,
	[TotalManhours] [numeric](12, 3) NULL,
	[TargetCPU] [numeric](10, 3) NULL,
	[TMS] [int] NULL,
	[CPUPrice] [numeric](10, 3) NULL,
	[TargetQty] [int] NULL,
	[TotalOutputQty] [int] NULL,
	[TotalCPU] [numeric](10, 3) NULL,
	[CPUSewerHR] [numeric](10, 3) NULL,
	[EFF] [numeric](10, 2) NULL,
	[RFT] [numeric](10, 2) NULL,
	[CumulateOfDays] [int] NULL,
	[DateRange] [varchar](15) NULL,
	[ProdOutput] [int] NULL,
	[Diff] [int] NULL,
	[Rate] [numeric](10, 2) NULL,
	[SewingReasonDesc] [nvarchar](1000) NULL,
	[SciDelivery] [date] NULL,
	[CDCodeNew] [varchar](5) NULL,
	[ProductType] [nvarchar](500) NULL,
	[FabricType] [nvarchar](500) NULL,
	[Lining] [varchar](20) NULL,
	[Gender] [varchar](10) NULL,
	[Construction] [nvarchar](50) NULL
) ON [PRIMARY]