CREATE TABLE [dbo].[P_WBScanRate](
	[Date] [date] NOT NULL,
	[Factory] [varchar](8) NOT NULL,
	[WBScanRate] [numeric](5, 2) NOT NULL,
	[TTLRFIDSewInlineQty] [int] NOT NULL,
	[TTLSewQty] [int] NOT NULL,
 CONSTRAINT [PK_P_WBScanRate] PRIMARY KEY CLUSTERED 
(
	[Date] ASC,
	[Factory] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[P_WBScanRate] ADD  CONSTRAINT [DF_P_WBScanRate_WBScanRate]  DEFAULT ((0)) FOR [WBScanRate]
GO

ALTER TABLE [dbo].[P_WBScanRate] ADD  CONSTRAINT [DF_P_WBScanRate_TTLRFIDSewInlineQty]  DEFAULT ((0)) FOR [TTLRFIDSewInlineQty]
GO

ALTER TABLE [dbo].[P_WBScanRate] ADD  CONSTRAINT [DF_P_WBScanRate_TTLSewQty]  DEFAULT ((0)) FOR [TTLSewQty]
GO
