CREATE TABLE [dbo].[P_WIPBySPLine]
(
	[MDivision]                         VARCHAR(8)      CONSTRAINT [DF_P_WIPBySPLine_MDivisionID]       NOT NULL DEFAULT (''), 
    [FactoryID]                         VARCHAR(8)      CONSTRAINT [DF_P_WIPBySPLine_FactoryID]       NOT NULL DEFAULT (''), 
    [SewingLineID]                      VARCHAR(60)     CONSTRAINT [DF_P_WIPBySPLine_SewingLineID]       NOT NULL DEFAULT (''), 
    [BuyerDelivery]                     DATE NULL, 
    [SCIDelivery]                       DATE NULL, 
    [SewInLine]                         DATE NULL, 
    [SewOffLine]                        DATE NULL, 
    [IDD]                               NVARCHAR(100)   CONSTRAINT [DF_P_WIPBySPLine_IDD]       NOT NULL DEFAULT (''), 
    [BrandID]                           VARCHAR(8)      CONSTRAINT [DF_P_WIPBySPLine_BrandID]       NOT NULL DEFAULT (''), 
    [SPNO]                              VARCHAR(13)     CONSTRAINT [DF_P_WIPBySPLine_SPNO]       NOT NULL DEFAULT (''), 
    [MasterSP]                          VARCHAR(13)     CONSTRAINT [DF_P_WIPBySPLine_MasterSP]       NOT NULL DEFAULT (''), 
    [IsBuyBack]                         VARCHAR(1)      CONSTRAINT [DF_P_WIPBySPLine_IsBuyBack]       NOT NULL DEFAULT (''), 
    [Cancelled]                         VARCHAR(1)      CONSTRAINT [DF_P_WIPBySPLine_Cancelled]       NOT NULL DEFAULT (''), 
    [CancelledStillNeedProd]            VARCHAR(1)      CONSTRAINT [DF_P_WIPBySPLine_CancelledStillNeedProd]       NOT NULL DEFAULT (''), 
    [Dest]                              VARCHAR(30)     CONSTRAINT [DF_P_WIPBySPLine_Dest]       NOT NULL DEFAULT (''), 
    [StyleID]                           VARCHAR(15)     CONSTRAINT [DF_P_WIPBySPLine_StyleID]       NOT NULL DEFAULT (''), 
    [OrderTypeID]                       VARCHAR(20)     CONSTRAINT [DF_P_WIPBySPLine_OrderTypeID]       NOT NULL DEFAULT (''), 
    [ShipMode]                          VARCHAR(30)     CONSTRAINT [DF_P_WIPBySPLine_ShipMode]       NOT NULL DEFAULT (''), 
    [PartialShipping]                   VARCHAR(1)      CONSTRAINT [DF_P_WIPBySPLine_PartialShipping]       NOT NULL DEFAULT (''), 
    [OrderNo]                           VARCHAR(30)     CONSTRAINT [DF_P_WIPBySPLine_OrderNo]       NOT NULL DEFAULT (''), 
    [PONO]                              VARCHAR(30)     CONSTRAINT [DF_P_WIPBySPLine_PONO]       NOT NULL DEFAULT (''), 
    [ProgramID]                         NVARCHAR(12)    CONSTRAINT [DF_P_WIPBySPLine_ProgramID]       NOT NULL DEFAULT (''), 
    [CDCodeID]                          VARCHAR(6)      CONSTRAINT [DF_P_WIPBySPLine_CDCodeID]       NOT NULL DEFAULT (''), 
    [CDCodeNew]                         VARCHAR(5)      CONSTRAINT [DF_P_WIPBySPLine_CDCodeNew]       NOT NULL DEFAULT (''), 
    [ProductType]                       NVARCHAR(100)   CONSTRAINT [DF_P_WIPBySPLine_ProductType]       NOT NULL DEFAULT (''), 
    [FabricType]                        NVARCHAR(100)   CONSTRAINT [DF_P_WIPBySPLine_FabricType]       NOT NULL DEFAULT (''), 
    [Lining]                            VARCHAR(20)     CONSTRAINT [DF_P_WIPBySPLine_Lining]       NOT NULL DEFAULT (''), 
    [Gender]                            VARCHAR(10)     CONSTRAINT [DF_P_WIPBySPLine_Gender]       NOT NULL DEFAULT (''), 
    [Construction]                      NVARCHAR(100)   CONSTRAINT [DF_P_WIPBySPLine_Construction]       NOT NULL, 
    [KPILETA]                           DATE NULL, 
    [SCHDLETA]                          DATE NULL, 
    [ActMTLETA_Master SP]               DATE NULL, 
    [SewMTLETA_SP]                      DATE NULL, 
    [PkgMTLETA_SP]                      DATE NULL, 
    [Cpu]                               NUMERIC(5, 3)   CONSTRAINT [DF_P_WIPBySPLine_Cpu]       NOT NULL DEFAULT ((0)), 
    [TTLCPU]                            NUMERIC(15, 3)  CONSTRAINT [DF_P_WIPBySPLine_TTLCPU]       NOT NULL DEFAULT ((0)), 
    [CPUClosed]                         NUMERIC(15, 3)  CONSTRAINT [DF_P_WIPBySPLine_CPUClosed]       NOT NULL DEFAULT ((0)), 
    [CPUBal]                            NUMERIC(15, 3)  CONSTRAINT [DF_P_WIPBySPLine_CPUBal]       NOT NULL DEFAULT ((0)), 
    [Article]                           NVARCHAR(500)   CONSTRAINT [DF_P_WIPBySPLine_Article]       NOT NULL DEFAULT (''), 
    [Qty]                               INT             CONSTRAINT [DF_P_WIPBySPLine_Qty]       NOT NULL DEFAULT ((0)), 
    [StandardOutput]                    NVARCHAR(1000)  CONSTRAINT [DF_P_WIPBySPLine_StandardOutput]       NOT NULL DEFAULT (''), 
    [OrigArtwork]                       NVARCHAR(800)   CONSTRAINT [DF_P_WIPBySPLine_OrigArtwork]       NOT NULL DEFAULT (''), 
    [AddedArtwork]                      NVARCHAR(800)   CONSTRAINT [DF_P_WIPBySPLine_AddedArtwork]       NOT NULL DEFAULT (''), 
    [BundleArtwork]                     NVARCHAR(800)   CONSTRAINT [DF_P_WIPBySPLine_BundleArtwork]       NOT NULL DEFAULT (''), 
    [SubProcessDest]                    NVARCHAR(900)   CONSTRAINT [DF_P_WIPBySPLine_SubProcessDest]       NOT NULL DEFAULT (''), 
    [EstCutDate]                        DATE NULL, 
    [1stCutDate]                        DATE NULL, 
    [CutQty]                            NUMERIC(14, 2)  CONSTRAINT [DF_P_WIPBySPLine_CutQty]       NOT NULL DEFAULT ((0)), 
    [RFIDCutQty]                        NUMERIC(10)     CONSTRAINT [DF_P_WIPBySPLine_RFIDCutQty]       NOT NULL DEFAULT ((0)), 
    [RFIDSewingLineInQty]               NUMERIC(6)      CONSTRAINT [DF_P_WIPBySPLine_RFIDSewingLineInQty]       NOT NULL DEFAULT ((0)), 
    [RFIDLoadingQty]                    NUMERIC(10)     CONSTRAINT [DF_P_WIPBySPLine_RFIDLoadingQty]       NOT NULL DEFAULT ((0)), 
    [RFIDEmbFarmInQty]                  NUMERIC(10)     CONSTRAINT [DF_P_WIPBySPLine_RFIDEmbFarmInQty]       NOT NULL DEFAULT ((0)), 
    [RFIDEmbFarmOutQty]                 NUMERIC(10)     CONSTRAINT [DF_P_WIPBySPLine_RFIDEmbFarmOutQty]       NOT NULL DEFAULT ((0)), 
    [RFIDBondFarmInQty]                 NUMERIC(10)     CONSTRAINT [DF_P_WIPBySPLine_RFIDBondFarmInQty]       NOT NULL DEFAULT ((0)), 
    [RFIDBondFarmOutQty]                NUMERIC(10)     CONSTRAINT [DF_P_WIPBySPLine_RFIDBondFarmOutQty]       NOT NULL DEFAULT ((0)), 
    [RFIDPrintFarmInQty]                NUMERIC(10)     CONSTRAINT [DF_P_WIPBySPLine_RFIDPrintFarmInQty]       NOT NULL DEFAULT ((0)), 
    [RFIDPrintFarmOutQty]               NUMERIC(10)     CONSTRAINT [DF_P_WIPBySPLine_RFIDPrintFarmOutQty]       NOT NULL DEFAULT ((0)), 
    [RFIDATFarmInQty]                   NUMERIC(10)     CONSTRAINT [DF_P_WIPBySPLine_RFIDATFarmInQty]       NOT NULL DEFAULT ((0)), 
    [RFIDATFarmOutQty]                  NUMERIC(10)     CONSTRAINT [DF_P_WIPBySPLine_RFIDATFarmOutQty]       NOT NULL DEFAULT ((0)), 
    [RFIDPadPrintFarmInQty]             NUMERIC(10)     CONSTRAINT [DF_P_WIPBySPLine_RFIDPadPrintFarmInQty]       NOT NULL DEFAULT ((0)), 
    [RFIDPadPrintFarmOutQty]            NUMERIC(10)     CONSTRAINT [DF_P_WIPBySPLine_RFIDPadPrintFarmOutQty]       NOT NULL DEFAULT ((0)), 
    [RFIDEmbossDebossFarmInQty]         NUMERIC(10)     CONSTRAINT [DF_P_WIPBySPLine_RFIDEmbossDebossFarmInQty]       NOT NULL DEFAULT ((0)), 
    [RFIDEmbossDebossFarmOutQty]        NUMERIC(10)     CONSTRAINT [DF_P_WIPBySPLine_RFIDEmbossDebossFarmOutQty]       NOT NULL DEFAULT ((0)), 
    [RFIDHTFarmInQty]                   NUMERIC(10)     CONSTRAINT [DF_P_WIPBySPLine_RFIDHTFarmInQty]       NOT NULL DEFAULT ((0)), 
    [RFIDHTFarmOutQty]                  NUMERIC(10)     CONSTRAINT [DF_P_WIPBySPLine_RFIDHTFarmOutQty]       NOT NULL DEFAULT ((0)), 
    [SubProcessStatus]                  VARCHAR(1)      CONSTRAINT [DF_P_WIPBySPLine_SubProcessStatus]       NOT NULL DEFAULT (''), 
    [EmbQty]                            NUMERIC(10)     CONSTRAINT [DF_P_WIPBySPLine_EmbQty]       NOT NULL DEFAULT ((0)), 
    [BondQty]                           NUMERIC(10)     CONSTRAINT [DF_P_WIPBySPLine_BondQty]       NOT NULL DEFAULT ((0)), 
    [PrintQty]                          NUMERIC(10)     CONSTRAINT [DF_P_WIPBySPLine_PrintQty]       NOT NULL DEFAULT ((0)), 
    [SewQty]                            NUMERIC(10)     CONSTRAINT [DF_P_WIPBySPLine_SewQty]       NOT NULL DEFAULT ((0)), 
    [SewBal]                            NUMERIC(10)     CONSTRAINT [DF_P_WIPBySPLine_SewBal]       NOT NULL DEFAULT ((0)), 
    [1stSewDate]                        DATE NULL, 
    [LastSewDate]                       DATE NULL, 
    [AverageDailyOutput]                INT             CONSTRAINT [DF_P_WIPBySPLine_AverageDailyOutput]       NOT NULL DEFAULT ((0)), 
    [EstOfflinedate]                    DATE NULL, 
    [ScannedQty]                        INT             CONSTRAINT [DF_P_WIPBySPLine_MDivisionID]       NOT NULL DEFAULT ((0)), 
    [PackedRate]                        NUMERIC(9, 4)   CONSTRAINT [DF_P_WIPBySPLine_PackedRate]       NOT NULL DEFAULT ((0)), 
    [TTLCTN]                            INT             CONSTRAINT [DF_P_WIPBySPLine_TTLCTN]       NOT NULL DEFAULT ((0)), 
    [FtyCTN]                            INT             CONSTRAINT [DF_P_WIPBySPLine_FtyCTN]       NOT NULL DEFAULT ((0)), 
    [cLogCTN]                           INT             CONSTRAINT [DF_P_WIPBySPLine_cLogCTN]       NOT NULL DEFAULT ((0)), 
    [CFACTN]                            INT             CONSTRAINT [DF_P_WIPBySPLine_CFACTN]       NOT NULL DEFAULT ((0)), 
    [InspDate]                          VARCHAR(500)    CONSTRAINT [DF_P_WIPBySPLine_InspDate]       NOT NULL DEFAULT (''), 
    [InspResult]                        VARCHAR(160)    CONSTRAINT [DF_P_WIPBySPLine_InspResult]       NOT NULL DEFAULT (''), 
    [CFAName]                           NVARCHAR(500)   CONSTRAINT [DF_P_WIPBySPLine_CFAName]       NOT NULL DEFAULT (''), 
    [ActPulloutDate]                    DATE NULL, 
    [KPIDeliveryDate]                   DATETIME NULL, 
    [UpdateDeliveryReason]              NVARCHAR(800)   CONSTRAINT [DF_P_WIPBySPLine_UpdateDeliveryReason]       NOT NULL DEFAULT (''), 
    [PlanDate]                          DATE NULL, 
    [SMR]                               VARCHAR(100)    CONSTRAINT [DF_P_WIPBySPLine_SMR]       NOT NULL DEFAULT (''), 
    [Handle]                            VARCHAR(100)    CONSTRAINT [DF_P_WIPBySPLine_Handle]       NOT NULL DEFAULT (''), 
    [Posmr]                             VARCHAR(100)    CONSTRAINT [DF_P_WIPBySPLine_Posmr]       NOT NULL DEFAULT (''), 
    [PoHandle]                          VARCHAR(100)    CONSTRAINT [DF_P_WIPBySPLine_PoHandle]       NOT NULL DEFAULT (''), 
    [MCHandle]                          VARCHAR(100)    CONSTRAINT [DF_P_WIPBySPLine_MCHandle]       NOT NULL DEFAULT (''), 
    [doxtype]                           VARCHAR(8)      CONSTRAINT [DF_P_WIPBySPLine_doxtype]       NOT NULL DEFAULT (''), 
    [SpecialMark]                       VARCHAR(50)     CONSTRAINT [DF_P_WIPBySPLine_SpecialMark]       NOT NULL DEFAULT (''), 
    [GlobalFoundationRange]             BIT             CONSTRAINT [DF_P_WIPBySPLine_GlobalFoundationRange]       NOT NULL DEFAULT ((0)), 
    [SampleReason]                      VARCHAR(5)      CONSTRAINT [DF_P_WIPBySPLine_SampleReason]       NOT NULL DEFAULT (''), 
    [TMS]                               NUMERIC(13, 3)  CONSTRAINT [DF_P_WIPBySPLine_TMS]       NOT NULL DEFAULT ((0)) 
)
