CREATE TABLE [dbo].[PurchaseList](
	[Factory] [varchar](8) NOT NULL,
	[Country of Destination] [varchar](30) NULL,
	[Country of Loading] [varchar](30) NULL,
	[Country of Loading (Original)] [varchar](30) NULL,
	[Supplier] [varchar](6) NULL,
	[Supplier Name] [nvarchar](25) NULL,
	[PINo Need] [varchar](1) NOT NULL,
	[Del. project by] [date] NULL,
	[Sup.Del. 1st cfm] [date] NULL,
	[Sup.Del Rvsd] [date] NULL,
	[SP#] [varchar](13) NULL,
	[Category] [varchar](20) NULL,
	[SMR] [nvarchar](69) NULL,
	[MR] [nvarchar](69) NULL,
	[PC Handle] [nvarchar](69) NULL,
	[PO Handle] [nvarchar](69) NULL,
	[PO SMR] [nvarchar](69) NULL,
	[Style] [varchar](15) NOT NULL,
	[Program] [varchar](12) NOT NULL,
	[Seq1] [varchar](3) NULL,
	[Seq2] [varchar](2) NULL,
	[Ref#] [varchar](20) NULL,
	[Brand Ref#] [varchar](50) NULL,
	[OrderType] [varchar](20) NULL,
	[Price] [numeric](16, 4) NULL,
	[Currency] [varchar](3) NULL,
	[Unit] [varchar](8) NULL,
	[Purchase Qty] [numeric](10, 2) NULL,
	[Ship Qty] [numeric](10, 2) NOT NULL,
	[Balance Qty] [numeric](11, 2) NULL,
	[Purchase FOC Qty] [numeric](10, 2) NULL,
	[Ship FOC Qty] [numeric](10, 2) NULL,
	[Balance FOC Qty] [numeric](11, 2) NULL,
	[Use Qty] [numeric](10, 2) NULL,
	[Loss Qty] [numeric](10, 2) NULL,
	[Amount(USD)] [numeric](18, 2) NULL,
	[In-Line Date] [date] NULL,
	[Season] [varchar](10) NOT NULL,
	[PI#] [varchar](25) NULL,
	[Size] [varchar](15) NULL,
	[S/Unit] [varchar](8) NULL,
	[Color ID] [varchar](6) NULL,
	[Color Desc] [nvarchar](150) NULL,
	[Actual ETA] [date] NULL,
	[PONo] [varchar](30) NULL,
	[Last ETA] [date] NULL,
	[Shipping Schedule] [date] NULL,
	[Estimate ETA] [date] NULL,
	[SCI Delivery] [date] NULL,
	[Buyer Delivery] [date] NULL,
	[CRD Date] [date] NULL,
	[Partial Shipment] [int] NULL,
	[Order Q’ty] [numeric](38, 0) NULL,
	[CustCD] [varchar](16) NULL,
	[Supplier Over Shipping Qty] [numeric](11, 2) NULL,
	[Supplier over shipping Qty %] [numeric](28, 13) NULL,
	[Input Qty] [numeric](38, 2) NULL,
	[Adject Qty] [numeric](38, 2) NULL,
	[Lead Time] [numeric](3, 0) NULL,
	[Order cfm Date] [date] NOT NULL,
	[CPU] [numeric](8, 3) NOT NULL,
	[Spec] [nvarchar](max) NULL,
	[Special] [nvarchar](max) NULL,
	[Long L/T Reason] [nvarchar](500) NULL,
	[WK#] [nvarchar](max) NULL,
	[Complete] [varchar](1) NOT NULL,
	[Stock C] [varchar](1) NOT NULL,
	[Shipping Mark] [varchar](10) NULL,
	[ECFA] [varchar](1) NOT NULL,
	[ECFA Duty] [numeric](6, 2) NULL,
	[Import Duty] [numeric](6, 2) NULL,
	[P/I Date] [date] NULL,
	[Materila Type] [varchar](20) NULL,
	[Ship Mode] [varchar](10) NULL,
	[Order List] [nvarchar](max) NULL,
	[Stock QTY (at PO Create Date)] [numeric](12, 1) NULL,
	[PR Comments] [nvarchar](max) NULL,
	[MR Comments] [nvarchar](max) NULL,
	[Buy Back] [varchar](1) NOT NULL,
	[Still need to Production] [varchar](1) NOT NULL,
	[Brand] [varchar](8) NOT NULL,
	[Supplier RefNo] [varchar](50) NULL,
	[Supplier Color] [nvarchar](max) NULL,
	[Remark] [nvarchar](max) NULL,
	[In the name of] [varchar](8) NULL,
	[For Other Brand] [varchar](1) NULL,
	[Eco thread SP#] [varchar](20) NULL,
	[without create M (for Eco RefNo)] [varchar](1) NULL,
	[Not output yet (for Eco RefNo)] [varchar](1) NULL,
	[Supplier Group] [nvarchar](20) NULL,
	[Supplier Delivery] [varchar](10) NULL,
	[Material] [varchar](10) NULL,
	[Mtl. Complete (Master SP)] [varchar](1) NULL,
	[Is 3rd Country] [varchar](1) NULL,
	[TransferBIDate] [datetime] NULL,
	[GMT complete] [varchar](1) NULL,
	[Last Buyer Delivery] [date] NULL,
	[Prod Item] [varchar](20) NULL,
	[Order Cancel] [varchar](1) NULL,
	[Mtl. O.Standing Reason] [nvarchar](510) NULL,
	[KPI L/ETA by Order List] [date] NULL,
	[Print Date] [date] NULL,
	[Ukey] [bigint] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
