CREATE TABLE [dbo].[PurchaseAnalysis] (
    [MrTeam]           VARCHAR (5)     NULL,
    [Brand]            VARCHAR (8)     NULL,
    [Style]            VARCHAR (15)    NULL,
    [Season]           VARCHAR (10)    NULL,
    [Category]         VARCHAR (30)    NULL,
    [Project]          VARCHAR (5)     NULL,
    [Factory]          VARCHAR (8)     NULL,
    [FactoryCountry]   VARCHAR (2)     NULL,
    [POSMR]            VARCHAR (10)    NULL,
    [POSMRNM]          VARCHAR (150)   NULL,
    [POMRHandle]       VARCHAR (10)    NULL,
    [POMRHandleNM]     VARCHAR (150)   NULL,
    [OrderConfirmDate] DATE            NULL,
    [SupplierGroup]    VARCHAR (100)   NULL,
    [Supplier]         VARCHAR (100)   NULL,
    [POID]             VARCHAR (13)    NULL,
    [Seq1]             VARCHAR (3)     NULL,
    [Seq2]             VARCHAR (2)     NULL,
    [FabricType]       VARCHAR (15)    NULL,
    [RefNo]            VARCHAR (36)    NULL,
    [MtlTypeId]        VARCHAR (20)    NULL,
    [POQty]            NUMERIC (15)    NULL,
    [POPrice]          NUMERIC (15, 4) NULL,
    [POAmount]         NUMERIC (15, 2) NULL,
    [RequestETD]       DATE            NULL,
    [RequestETD_Y]     INT             NULL,
    [RequestETD_M]     INT             NULL,
    [MinScheduleDate]  DATE            NULL,
    [EstLoadDate]      DATE            NULL,
    [ActLoadDate]      DATE            NULL,
    [EstETA]           DATE            NULL,
    [ActEta]           DATE            NULL,
    [ShipETA]          DATE            NULL,
    [IsDelay]          BIT             NULL,
    [Count_Delay]      INT             NULL,
    [Count_OnTime]     INT             NULL,
    [ShipStatus]       VARCHAR (10)    NULL
);

