CREATE TABLE [dbo].[SewingLineScheduleBI](
	[APSNo] [int] NULL,
	[SewingLineID] [varchar](2) NULL,
	[SewingDay] [date] NULL,
	[SewingStartTime] [datetime] NULL,
	[SewingEndTime] [datetime] NULL,
	[MDivisionID] [varchar](8) NULL,
	[FactoryID] [varchar](8) NULL,
	[PO] [nvarchar](max) NULL,
	[POCount] [bigint] NULL,
	[SP] [nvarchar](max) NULL,
	[SPCount] [int] NULL,
	[EarliestSCIdelivery] [date] NULL,
	[LatestSCIdelivery] [date] NULL,
	[EarliestBuyerdelivery] [date] NULL,
	[LatestBuyerdelivery] [date] NULL,
	[Category] [nvarchar](max) NULL,
	[Colorway] [nvarchar](max) NULL,
	[ColorwayCount] [bigint] NULL,
	[CDCode] [nvarchar](max) NULL,
	[ProductionFamilyID] [nvarchar](max) NULL,
	[Style] [nvarchar](max) NULL,
	[StyleCount] [bigint] NULL,
	[OrderQty] [int] NULL,
	[AlloQty] [int] NULL,
	[StardardOutputPerDay] [float] NULL,
	[CPU] [float] NULL,
	[WorkHourPerDay] [float] NULL,
	[StardardOutputPerHour] [float] NULL,
	[Efficienycy] [numeric](10, 2) NULL,
	[ScheduleEfficiency] [numeric](11, 2) NULL,
	[LineEfficiency] [numeric](11, 2) NULL,
	[LearningCurve] [numeric](17, 2) NULL,
	[SewingInline] [datetime] NULL,
	[SewingOffline] [datetime] NULL,
	[PFRemark] [varchar](1) NULL,
	[MTLComplete] [varchar](1) NULL,
	[KPILETA] [date] NULL,
	[MTLETA] [date] NULL,
	[ArtworkType] [nvarchar](max) NULL,
	[InspectionDate] [date] NULL,
	[Remarks] [nvarchar](max) NULL,
	[CuttingOutput] [numeric](38, 2) NULL,
	[SewingOutput] [int] NULL,
	[ScannedQty] [int] NULL,
	[ClogQty] [int] NULL,
	[Sewer] [int] NULL,
	[SewingCPU] [numeric](10, 2) NULL,
	[BrandID] [nvarchar](8) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
