CREATE TABLE [dbo].[T_AdiCompReport](
	[Year] [varchar](4) NULL,
	[Month] [varchar](2) NULL,
	[ID] [varchar](13) NULL,
	[SalesID] [varchar](5) NULL,
	[SalesName] [nvarchar](50) NULL,
	[Article] [varchar](8) NULL,
	[ArticleName] [nvarchar](60) NULL,
	[ProductionDate] [date] NULL,
	[DefectMainID] [varchar](2) NULL,
	[DefectSubID] [varchar](1) NULL,
	[FOB] [numeric](5, 2) NULL,
	[Qty] [numeric](3, 0) NULL,
	[ValueinUSD] [numeric](8, 4) NULL,
	[ValueINExRate] [numeric](7, 2) NULL,
	[OrderID] [varchar](13) NULL,
	[RuleNo] [numeric](1, 0) NULL,
	[UKEY] [bigint] NULL,
	[BrandID] [varchar](8) NULL,
	[FactoryID] [varchar](8) NULL,
	[SuppID] [varchar](6) NULL,
	[Refno] [varchar](23) NULL,
	[IsEM] [bit] NULL,
	[StyleID] [varchar](15) NULL,
	[ProgramID] [varchar](12) NULL,
	[Supplier] [varchar](6) NULL,
	[SupplierName] [nvarchar](12) NULL,
	[DefectMain] [nvarchar](260) NULL,
	[DefectSub] [nvarchar](260) NULL,
	[Responsibility] [varchar](2) NULL,
	[MDivisionID] [varchar](8) NULL,
	[TableUkey] [bigint] NULL
) ON [PRIMARY]
GO