CREATE TABLE [dbo].[T_AnnualSalesReport](
	[Source] [varchar](8) NULL,
	[ID] [varchar](13) NULL,
	[BrandID] [varchar](8) NULL,
	[StyleID] [varchar](15) NULL,
	[SeasonID] [varchar](10) NULL,
	[FactoryID] [varchar](8) NULL,
	[BuyerDelivery] [date] NULL,
	[SCIDelivery] [date] NULL,
	[CPU] [numeric](8, 3) NULL,
	[TotalCPU] [numeric](19, 4) NULL,
	[Qty] [numeric](6, 0) NULL,
	[FOCQty] [numeric](6, 0) NULL,
	[CurrencyID] [varchar](4) NULL,
	[USDUnitPrice] [numeric](30, 12) NULL,
	[USDAmount] [numeric](38, 6) NULL,
	[CDCodeID] [varchar](6) NULL,
	[Category] [varchar](6) NULL,
	[SMR] [nvarchar](58) NULL,
	[MR] [nvarchar](58) NULL,
	[POHandle] [nvarchar](58) NULL,
	[Region] [varchar](2) NULL,
	[MDivisionID] [varchar](8) NULL,
	[ProgramID] [varchar](12) NULL,
	[StyleUkey] [bigint] NULL,
	[COO] [nvarchar](30) NULL,
	[ProductionFamily] [varchar](20) NULL,
	[Gender] [varchar](10) NULL,
	[CDCodeNew] [varchar](5) NULL,
	[Description] [varchar](100) NULL,
	[Cust Date] [date] NULL,
	[Orig. Buyer Delivery] [date] NULL,
	[TransferBIDate] [date] NULL,
	[Project] [varchar](5) NULL, 
    [Ukey] [bigint] NULL
) ON [PRIMARY]
GO