CREATE TABLE [dbo].[T_MtlStatusAnalisis](
	[WK#] [varchar](13) NOT NULL,
	[Loading Country] [varchar](2) NULL,
	[Loading Port] [varchar](20) NULL,
	[Shipmode] [varchar](10) NULL,
	[Close Date] [date] NULL,
	[ETD] [date] NULL,
	[Sche. ETA] [date] NOT NULL,
	[ETA] [date] NULL,
	[Arrive WH date] [date] NULL,
	[KPI L/ETA] [date] NULL,
	[Prod.LT] [int] NULL,
	[WK# Factory] [varchar](8) NULL,
	[Factory] [varchar](8) NULL,
	[SP No] [varchar](13) NULL,
	[SEQ] [varchar](max) NULL,
	[Category] [nvarchar](50) NULL,
	[PF ETA] [date] NULL,
	[SewinLine] [date] NULL,
	[Buyer Delivery] [date] NULL,
	[SCI Delivery] [date] NULL,
	[PO SMR] [nvarchar](69) NULL,
	[PO Handle] [nvarchar](69) NULL,
	[SMR] [nvarchar](69) NULL,
	[MR] [nvarchar](69) NULL,
	[PC Handle] [nvarchar](69) NULL,
	[Style] [varchar](15) NULL,
	[SP List] [varchar](max) NULL,
	[PO Qty] [numeric](10, 0) NULL,
	[Project] [varchar](5) NULL,
	[Early Ship Reason] [varchar](max) NULL,
	[WK# Handle] [nvarchar](69) NULL,
	[MTL Confirm] [varchar](1) NULL,
	[Duty] [nvarchar](600) NULL,
	[PF Remark] [varchar](max) NULL,
	[Type] [varchar](10) NULL,
	[Ukey] [bigint] NOT NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO