CREATE TABLE [dbo].[T_MtltoFTYAnalysis](
	[Factory] [varchar](8) NULL,
	[Country] [varchar](2) NULL,
	[Brand] [varchar](8) NULL,
	[WeaveType] [varchar](20) NULL,
	[ETD] [date] NULL,
	[ETA] [date] NULL,
	[Close Date] [date] NULL,
	[Act. Date] [date] NULL,
	[Category] [nvarchar](50) NULL,
	[OrderID] [varchar](13) NULL,
	[Seq1] [varchar](3) NULL,
	[Seq2] [varchar](2) NULL,
	[Order Cfm Date] [date] NULL,
	[Sci Delivery] [date] NULL,
	[Refno] [varchar](23) NULL,
	[SCI Refno] [varchar](30) NULL,
	[SuppID] [varchar](6) NULL,
	[SuppName] [nvarchar](12) NULL,
	[CurrencyID] [varchar](3) NULL,
	[Currency Rate] [numeric](2, 0) NULL,
	[Price] [numeric](16, 4) NULL,
	[Price (TWD)] [numeric](16, 4) NULL,
	[Unit] [varchar](8) NULL,
	[Po Qty] [numeric](10, 2) NULL,
	[Po Foc] [numeric](10, 2) NULL,
	[ShipQty] [numeric](12, 2) NULL,
	[ShipFoc] [numeric](12, 2) NULL,
	[TTShipQty] [numeric](12, 2) NULL,
	[ShipAmt (TWD)] [numeric](16, 4) NULL,
	[Fabric Junk] [varchar](1) NULL,
	[WK ID] [varchar](13) NULL,
	[Shipment Term] [varchar](5) NULL,
	[Fabric Type] [varchar](10) NULL,
	[PINO] [varchar](25) NULL,
	[PI DATE] [date] NULL,
	[Color] [varchar](6) NULL,
	[Color Name] [nvarchar](150) NULL,
	[Season] [varchar](10) NULL,
	[PCHandle] [nvarchar](100) NULL,
	[POHandle] [nvarchar](100) NULL,
	[POSMR] [nvarchar](100) NULL,
	[Style] [varchar](15) NULL,
	[OrderType] [varchar](20) NULL,
	[ShipModeID] [varchar](10) NULL,
	[Supp 1st Cfm Date] [date] NULL,
	[Brand Supp Code] [varchar](6) NULL,
	[Brand Supp Name] [nvarchar](100) NULL,
	[Country of Loading] [varchar](30) NULL,
	[SupdelRvsd] [date] NULL,
	[ProdItem] [varchar](20) NULL,
	[KPILETA] [date] NULL,
	[MaterialConfirm] [varchar](1) NULL,
	[SupplierGroup] [varchar](8) NULL,
	[TransferBIDate] [date] NULL,
	[Ukey] [bigint] NULL
) ON [PRIMARY]
GO
