CREATE TABLE [dbo].[T_OrderList](
	[StyleUkey] [bigint] NULL,
	[Factory] [varchar](12) NULL,
	[FtyCountryID] [varchar](2) NULL,
	[MDivisionID] [varchar](8) NULL,
	[BuyerDelivery] [date] NULL,
	[SCIDelivery] [date] NULL,
	[Key] [varchar](6) NULL,
	[HalfKey] [varchar](8) NULL,
	[Buyer Key] [varchar](6) NULL,
	[Buyer HalfKey] [varchar](8) NULL,
	[Category] [varchar](50) NULL,
	[DevSample] [varchar](1) NULL,
	[PONO] [varchar](30) NULL,
	[POID] [varchar](30) NULL,
	[SPNO] [varchar](13) NULL,
	[StyleID] [varchar](15) NULL,
	[Season] [varchar](10) NULL,
	[Brand] [varchar](8) NULL,
	[Program] [varchar](12) NULL,
	[CDCodeID] [varchar](6) NULL,
	[ProductionFamilyID] [varchar](20) NULL,
	[CPU] [numeric](8, 3) NULL,
	[Qty] [numeric](6, 0) NULL,
	[TTLCPU] [numeric](36, 4) NULL,
	[Junk] [varchar](1) NULL,
	[Need Production] [varchar](1) NULL,
	[Keep Panels] [varchar](1) NULL,
	[Buy Back] [varchar](1) NULL,
	[Buy Back Reason] [varchar](20) NULL,
	[TTL_AT (CPU)] [numeric](38, 6) NULL,
	[TTL_AT (HAND) (CPU)] [numeric](38, 6) NULL,
	[TTL_AT (MACHINE) (CPU)] [numeric](38, 6) NULL,
	[TTL_AUTO-TEMPLATE (CPU)] [numeric](38, 6) NULL,
	[TTL_B-HOT PRESS(BONDING) (CPU)] [numeric](38, 6) NULL,
	[TTL_BIG HOT PRESS (CPU)] [numeric](38, 6) NULL,
	[TTL_BONDING (HAND) (CPU)] [numeric](38, 6) NULL,
	[TTL_BONDING (MACHINE) (CPU)] [numeric](38, 6) NULL,
	[TTL_CUTTING (CPU)] [numeric](38, 6) NULL,
	[TTL_DIE CUT (CPU)] [numeric](38, 6) NULL,
	[TTL_DIE-CUT (CPU)] [numeric](38, 6) NULL,
	[TTL_DOWN (CPU)] [numeric](38, 6) NULL,
	[TTL_DOWN FILLING (CPU)] [numeric](38, 6) NULL,
	[TTL_EMBOSS/DEBOSS (Price)] [numeric](38, 6) NULL,
	[TTL_EMBROIDERY (Price)] [numeric](38, 6) NULL,
	[TTL_EMBROIDERY (STITCH in thousands)] [numeric](38, 6) NULL,
	[TTL_EYEBUTTON (CPU)] [numeric](38, 6) NULL,
	[TTL_FEEDOFARM (CPU)] [numeric](38, 6) NULL,
	[TTL_Fusible (CPU)] [numeric](38, 6) NULL,
	[TTL_GARMENT DYE (Price)] [numeric](38, 6) NULL,
	[TTL_GMT WASH (Price)] [numeric](38, 6) NULL,
	[TTL_HEAT TRANSFER (CPU)] [numeric](38, 6) NULL,
	[TTL_INSPECTION (CPU)] [numeric](38, 6) NULL,
	[TTL_INTENSIVE MACHINE (CPU)] [numeric](38, 6) NULL,
	[TTL_LASER (CPU)] [numeric](38, 6) NULL,
	[TTL_LASER CUTTER (CPU)] [numeric](38, 6) NULL,
	[TTL_PAD PRINTING (Price)] [numeric](38, 6) NULL,
	[TTL_PRINTING (PCS)] [numeric](38, 6) NULL,
	[TTL_PRINTING (Price)] [numeric](38, 6) NULL,
	[TTL_REAL FLATSEAM (CPU)] [numeric](38, 6) NULL,
	[TTL_ROLLER SUBLIMATION (CPU)] [numeric](38, 6) NULL,
	[TTL_S-HOT PRESS(BONDING) (CPU)] [numeric](38, 6) NULL,
	[TTL_S-HOT PRESS(HT) (CPU)] [numeric](38, 6) NULL,
	[TTL_SEAM TAPING MACHINE (CPU)] [numeric](38, 6) NULL,
	[TTL_SMALL HOT PRESS (CPU)] [numeric](38, 6) NULL,
	[TTL_SUBLIMATION PRINT (CPU)] [numeric](38, 6) NULL,
	[TTL_SUBLIMATION ROLLER (CPU)] [numeric](38, 6) NULL,
	[TTL_ULTRASONIC MACHINE (CPU)] [numeric](38, 6) NULL,
	[TTL_VELCRO MACHINE (CPU)] [numeric](38, 6) NULL,
	[TTL_ZIG ZAG (CPU)] [numeric](38, 6) NULL,
	[TTL_PRINTING PPU (PPU)] [numeric](38, 6) NULL,
	[Sew_Qty by Rate] [numeric](10, 4) NULL,
	[Amount (USD)] [numeric](38, 6) NULL,
	[Sew_Qty] [numeric](6, 0) NULL,
	[Shortage] [numeric](6, 0) NULL,
	[Project] [varchar](5) NULL,
	[CustDate] [date] NULL,
	[KPI L/ETA] [date] NULL,
	[SCHD L/ETA(Master SP)] [date] NULL,
	[LastProductionDate] [date] NULL,
	[TTL_PAD PRINTING (PCS)] [numeric](38, 6) NULL,
	[Garment L/T] [numeric](3, 0) NULL,
	[Delay Reason Code Production ID] [varchar](4) NULL,
	[Delay Reason Code Production DESC] [varchar](100) NULL,
	[CDate] [date] NULL,
	[PFETA] [date] NULL,
	[New CD Code] [varchar](5) NULL,
	[Product Type] [varchar](500) NULL,
	[Fabric Type] [varchar](500) NULL,
	[Lining] [varchar](500) NULL,
	[Construction] [varchar](500) NULL,
	[Gender] [varchar](500) NULL,
	[OrigBuyerDelivery] [date] NULL,
	[Hanger Pack] [varchar](1) NULL,
	[Tissue Paper] [varchar](1) NULL,
	[PlanDate] [date] NULL,
	[TransferBIDate] [datetime] NULL,
	[FtyZone] [varchar](6) NULL,
	[OrderType] [varchar](20) NULL,
	[Is Mix Marker] [varchar](1) NULL,
	[Cutting Combo] [varchar](13) NULL,
	[New C/O] [nvarchar](50) NULL,
	[Buyer] [varchar](8) NULL,
	[OriQty] [numeric](8, 0) NULL,
	[Each Cons.] [datetime] NULL,
	[SCHD L/ETD(Master SP)] [date] NULL,
	[Act.MTL ETA] [date] NULL,
	[Act.MTL ETA (N/I Repl.)] [date] NULL,
	[Sew. MTL ETA(SP)] [date] NULL,
	[Pkg. MTL ETA(SP)] [date] NULL,
	[MTL Cmplt (Master SP)] [varchar](10) NULL,
	[MTL Cmplt (SP)] [varchar](1) NULL,
	[Pack_LETA] [date] NULL,
	[PF Remark] [varchar](max) NULL,
	[FOB1] [numeric](16, 4) NULL,
	[CMPQ] [numeric](16, 4) NULL,
	[SewLine] [varchar](60) NULL,
	[Last Sewing Output Date] [date] NULL,
	[Sewing InLine (SP)] [date] NULL,
	[Sewing OffLine (SP)] [date] NULL,
	[Earliest Sewing inline (Combo)] [date] NULL,
	[Latest Sewing Offine (Combo)] [date] NULL,
	[Exp. PullDate] [date] NULL,
	[Act PullOut] [date] NULL,
	[GMT. Ship Times] [int] NULL,
	[GMT. Ship Qty] [numeric](38, 0) NULL,
	[Gmt Complete] [varchar](1) NULL,
	[Country] [varchar](30) NULL,
	[ShipMode] [varchar](30) NULL,
	[Handle] [nvarchar](69) NULL,
	[SMR] [nvarchar](69) NULL,
	[PO Handle] [nvarchar](69) NULL,
	[PO SMR] [nvarchar](69) NULL,
	[PC SMR] [nvarchar](69) NULL,
	[PC Handle] [nvarchar](69) NULL,
	[MC Handle] [nvarchar](69) NULL,
	[Buy Month] [varchar](16) NULL,
	[Special Cust] [varchar](1) NULL,
	[Delay Supp] [varchar](500) NULL,
	[Dest] [varchar](2) NULL,
	[MR Team] [varchar](5) NULL,
	[Currency] [varchar](3) NULL,
	[Amount] [numeric](38, 6) NULL,
	[Ori_Amount] [numeric](38, 6) NULL,
	[Ori_Amount (USD)] [numeric](38, 6) NULL,
	[Unit] [varchar](8) NULL,
	[Cut in line] [date] NULL,
	[Cut off Line] [date] NULL,
	[I plandate] [date] NULL,
	[Mtl Delay] [varchar](1) NULL,
	[Model] [varchar](25) NULL,
	[VAS/SHAS] [varchar](1) NULL,
	[Customize1] [varchar](30) NULL,
	[Customize2] [varchar](30) NULL,
	[Customize3] [varchar](30) NULL,
	[SpecMark] [varchar](506) NULL,
	[First Production Date] [date] NULL,
	[Process] [nvarchar](60) NULL,
	[FromType] [varchar](2) NULL,
	[TmpSewing] [numeric](26, 3) NULL,
	[CPURate] [numeric](3, 1) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]