CREATE TABLE [dbo].[T_OrderList](
	[StyleUkey] [bigint] NULL,
	[Factory] [varchar](12) NOT NULL,
	[FtyCountryID] [varchar](2) NULL,
	[MDivisionID] [varchar](8) NULL,
	[BuyerDelivery] [date] NULL,
	[SCIDelivery] [date] NULL,
	[Key] [varchar](6) NULL,
	[HalfKey] [varchar](8) NULL,
	[Buyer Key] [varchar](6) NULL,
	[Buyer HalfKey] [varchar](8) NULL,
	[Category] [varchar](50) NULL,
	[DevSample] [varchar](1) NULL,
	[PONO] [varchar](30) NULL,
	[POID] [varchar](30) NULL,
	[SPNO] [varchar](13) NOT NULL,
	[StyleID] [varchar](15) NULL,
	[Season] [varchar](10) NULL,
	[Brand] [varchar](8) NULL,
	[Program] [varchar](12) NULL,
	[CDCodeID] [varchar](6) NULL,
	[ProductionFamilyID] [varchar](20) NULL,
	[CPU] [numeric](8, 3) NULL,
	[Qty] [numeric](6, 0) NULL,
	[TTLCPU] [numeric](36, 4) NULL,
	[Junk] [varchar](1) NULL,
	[Need Production] [varchar](1) NULL,
	[Keep Panels] [varchar](1) NULL,
	[Buy Back] [varchar](1) NULL,
	[Buy Back Reason] [varchar](20) NULL,
	[Sew_Qty by Rate] [numeric](10, 4) NULL,
	[Amount (USD)] [numeric](38, 6) NULL,
	[Sew_Qty] [numeric](6, 0) NULL,
	[Shortage] [numeric](6, 0) NULL,
	[Project] [varchar](5) NULL,
	[CustDate] [date] NULL,
	[KPI L/ETA] [date] NULL,
	[SCHD L/ETA(Master SP)] [date] NULL,
	[LastProductionDate] [date] NULL,
	[TTL_PAD PRINTING (PCS)] [numeric](38, 6) NULL,
	[Garment L/T] [numeric](3, 0) NULL,
	[Delay Reason Code Production ID] [varchar](4) NULL,
	[Delay Reason Code Production DESC] [varchar](100) NULL,
	[CDate] [date] NULL,
	[PFETA] [date] NULL,
	[New CD Code] [varchar](5) NULL,
	[Product Type] [varchar](500) NULL,
	[Fabric Type] [varchar](500) NULL,
	[Lining] [varchar](500) NULL,
	[Construction] [varchar](500) NULL,
	[Gender] [varchar](500) NULL,
	[OrigBuyerDelivery] [date] NULL,
	[Hanger Pack] [varchar](1) NULL,
	[Tissue Paper] [varchar](1) NULL,
	[PlanDate] [date] NULL,
	[TransferBIDate] [datetime] NULL,
	[FtyZone] [varchar](6) NULL,
	[OrderType] [varchar](20) NULL,
	[Is Mix Marker] [varchar](1) NULL,
	[Cutting Combo] [varchar](13) NULL,
	[New C/O] [nvarchar](50) NULL,
	[Buyer] [varchar](8) NULL,
	[OriQty] [numeric](8, 0) NULL,
	[Each Cons.] [datetime] NULL,
	[SCHD L/ETD(Master SP)] [date] NULL,
	[Act.MTL ETA] [date] NULL,
	[Act.MTL ETA (N/I Repl.)] [date] NULL,
	[Sew. MTL ETA(SP)] [date] NULL,
	[Pkg. MTL ETA(SP)] [date] NULL,
	[MTL Cmplt (Master SP)] [varchar](10) NULL,
	[MTL Cmplt (SP)] [varchar](1) NULL,
	[Pack_LETA] [date] NULL,
	[PF Remark] [varchar](max) NULL,
	[FOB1] [numeric](16, 4) NULL,
	[CMPQ] [numeric](16, 4) NULL,
	[SewLine] [varchar](60) NULL,
	[Last Sewing Output Date] [date] NULL,
	[Sewing InLine (SP)] [date] NULL,
	[Sewing OffLine (SP)] [date] NULL,
	[Earliest Sewing inline (Combo)] [date] NULL,
	[Latest Sewing Offine (Combo)] [date] NULL,
	[Exp. PullDate] [date] NULL,
	[Act PullOut] [date] NULL,
	[GMT. Ship Times] [int] NULL,
	[GMT. Ship Qty] [numeric](38, 0) NULL,
	[Gmt Complete] [varchar](1) NULL,
	[Country] [varchar](30) NULL,
	[ShipMode] [varchar](30) NULL,
	[Handle] [nvarchar](69) NULL,
	[SMR] [nvarchar](69) NULL,
	[PO Handle] [nvarchar](69) NULL,
	[PO SMR] [nvarchar](69) NULL,
	[PC SMR] [nvarchar](69) NULL,
	[PC Handle] [nvarchar](69) NULL,
	[MC Handle] [nvarchar](69) NULL,
	[Buy Month] [varchar](16) NULL,
	[Special Cust] [varchar](1) NULL,
	[Delay Supp] [varchar](500) NULL,
	[Dest] [varchar](2) NULL,
	[MR Team] [varchar](5) NULL,
	[Currency] [varchar](3) NULL,
	[Amount] [numeric](38, 6) NULL,
	[Ori_Amount] [numeric](38, 6) NULL,
	[Ori_Amount (USD)] [numeric](38, 6) NULL,
	[Unit] [varchar](8) NULL,
	[Cut in line] [date] NULL,
	[Cut off Line] [date] NULL,
	[I plandate] [date] NULL,
	[Mtl Delay] [varchar](1) NULL,
	[Model] [varchar](25) NULL,
	[VAS/SHAS] [varchar](1) NULL,
	[Customize1] [varchar](30) NULL,
	[Customize2] [varchar](30) NULL,
	[Customize3] [varchar](30) NULL,
	[SpecMark] [varchar](506) NULL,
	[First Production Date] [date] NULL,
	[Process] [nvarchar](60) NULL,
	[FromType] [varchar](2) NOT NULL,
	[TmpSewing] [numeric](26, 3) NULL,
	[CPURate] [numeric](3, 1) NULL,
	[Sew. MTL ETA(SP excl. Repl.)] [date] NULL,
	[Subcon In Type] [varchar](50) NULL,
	[EMBROIDERY (STITCH)] [numeric](38, 6) NULL,
	[WELTED M/C (TMS)] [numeric](38, 6) NULL,
	[PRINTING PPU (PPU)] [numeric](38, 6) NULL,
	[GENERAL AFFAIR (Price)] [numeric](38, 6) NULL,
	[GARMENT DYE (Price)] [numeric](38, 6) NULL,
	[BONDING (HAND) (TMS)] [numeric](38, 6) NULL,
	[BLINDSTITCH (TMS)] [numeric](38, 6) NULL,
	[QUILTING (Price)] [numeric](38, 6) NULL,
	[SEWING (TMS)] [numeric](38, 6) NULL,
	[REPAIR GARMENT (Price)] [numeric](38, 6) NULL,
	[GMT WASH (PCS)] [numeric](38, 6) NULL,
	[COVERSTITCH CYLINDER (TMS)] [numeric](38, 6) NULL,
	[RECOAT GARMENT (Price)] [numeric](38, 6) NULL,
	[GARMENT DYE (PCS)] [numeric](38, 6) NULL,
	[HEAT SET PLEAT (PCS)] [numeric](38, 6) NULL,
	[QUILTING(HAND) (TMS)] [numeric](38, 6) NULL,
	[COVERSTITCH L-CUTTER (TMS)] [numeric](38, 6) NULL,
	[EMBOSS/DEBOSS (PCS)] [numeric](38, 6) NULL,
	[AUTO-TEMPLATE QT (TMS)] [numeric](38, 6) NULL,
	[EM/DEBOSS (I/H) (TMS)] [numeric](38, 6) NULL,
	[BONDING (MACHINE) (TMS)] [numeric](38, 6) NULL,
	[ULTRASONIC-ELASTIC (TMS)] [numeric](38, 6) NULL,
	[AE RING-KNIFE (TMS)] [numeric](38, 6) NULL,
	[D-CHAIN ZIG ZAG (TMS)] [numeric](38, 6) NULL,
	[PAD PRINTING (PCS)] [numeric](38, 6) NULL,
	[POCKET WELT (Price)] [numeric](38, 6) NULL,
	[VELCRO MACHINE (TMS)] [numeric](38, 6) NULL,
	[EMBROIDERY TMS (TMS)] [numeric](38, 6) NULL,
	[INSPECTION (TMS)] [numeric](38, 6) NULL,
	[PRESSING (TMS)] [numeric](38, 6) NULL,
	[EMBROIDERY EYELET (TMS)] [numeric](38, 6) NULL,
	[INTENSIVE MACHINE (TMS)] [numeric](38, 6) NULL,
	[EMBROIDERY (Price)] [numeric](38, 6) NULL,
	[AE RING-ULTRASONIC (TMS)] [numeric](38, 6) NULL,
	[PRINTING (PCS)] [numeric](38, 6) NULL,
	[EYEBUTTON (TMS)] [numeric](38, 6) NULL,
	[VELCROED M/C (TMS)] [numeric](38, 6) NULL,
	[AT (MACHINE) (TMS)] [numeric](38, 6) NULL,
	[DOWN FILLING (TMS)] [numeric](38, 6) NULL,
	[AUTO BELT LOOPER (TMS)] [numeric](38, 6) NULL,
	[SUBLIMATION ROLLER (TMS)] [numeric](38, 6) NULL,
	[ULTRASONIC (TMS)] [numeric](38, 6) NULL,
	[SP_THREAD (Price)] [numeric](38, 6) NULL,
	[MAINTENANCE (Price)] [numeric](38, 6) NULL,
	[AUTO POCKET WELT (TMS)] [numeric](38, 6) NULL,
	[SEAM TAPING MACHINE (TMS)] [numeric](38, 6) NULL,
	[EM/DEBOSS (MOLD) (Price)] [numeric](38, 6) NULL,
	[HEAT SET PLEAT (Price)] [numeric](38, 6) NULL,
	[STATIONERY (Price)] [numeric](38, 6) NULL,
	[PRINTING (Price)] [numeric](38, 6) NULL,
	[B-HOT PRESS(BONDING) (TMS)] [numeric](38, 6) NULL,
	[ULTRASONIC-LABEL ASM (TMS)] [numeric](38, 6) NULL,
	[FARM OUT QUILTING (Price)] [numeric](38, 6) NULL,
	[EMBOSS/DEBOSS (Price)] [numeric](38, 6) NULL,
	[LASER (TMS)] [numeric](38, 6) NULL,
	[ROLLER SUBLIMATION (TMS)] [numeric](38, 6) NULL,
	[CUTTING (TMS)] [numeric](38, 6) NULL,
	[SEAMSEAL (TMS)] [numeric](38, 6) NULL,
	[3C EQUIPMENT (Price)] [numeric](38, 6) NULL,
	[DOWN (TMS)] [numeric](38, 6) NULL,
	[ULTRASONIC-TAPE CUT (TMS)] [numeric](38, 6) NULL,
	[EMB_THREAD (Price)] [numeric](38, 6) NULL,
	[PAD PRINTING (Price)] [numeric](38, 6) NULL,
	[CHEMICAL (Price)] [numeric](38, 6) NULL,
	[BH-TWICE FOR WB (TMS)] [numeric](38, 6) NULL,
	[PACKING (TMS)] [numeric](38, 6) NULL,
	[POLYBAG (Price)] [numeric](38, 6) NULL,
	[LASER-GALVANOMETER (TMS)] [numeric](38, 6) NULL,
	[SMALL HOT PRESS-LONG (TMS)] [numeric](38, 6) NULL,
	[AT (HAND) (TMS)] [numeric](38, 6) NULL,
	[JOKERTAG (TMS)] [numeric](38, 6) NULL,
	[BH-TWICE FOR PLACKET (TMS)] [numeric](38, 6) NULL,
	[ZIG ZAG (TMS)] [numeric](38, 6) NULL,
	[DIE CUT (TMS)] [numeric](38, 6) NULL,
	[FARM OUT QUILTING (PCS)] [numeric](38, 6) NULL,
	[HEAT TRANSFER (PANEL)] [numeric](38, 6) NULL,
	[AUTO-TEMPLATE (TMS)] [numeric](38, 6) NULL,
	[SHIPPING (Price)] [numeric](38, 6) NULL,
	[INDIRECT MANPOWER (TMS)] [numeric](38, 6) NULL,
	[SUBLIMATION PRINT (TMS)] [numeric](38, 6) NULL,
	[REAL FLATSEAM (TMS)] [numeric](38, 6) NULL,
	[FEEDOFARM (TMS)] [numeric](38, 6) NULL,
	[B-HOT PRESS(SUB-PRT) (TMS)] [numeric](38, 6) NULL,
	[GMT WASH (Price)] [numeric](38, 6) NULL,
	[FUSIBLE (TMS)] [numeric](38, 6) NULL,
	[DIE-CUT (TMS)] [numeric](38, 6) NULL,
	[S-HOT PRESS(BONDING) (TMS)] [numeric](38, 6) NULL,
	[CUTTING TAPE (Price)] [numeric](38, 6) NULL,
	[HEAT TRANSFER (TMS)] [numeric](38, 6) NULL,
	[S-HOT PRESS(HT) (TMS)] [numeric](38, 6) NULL,
	[LASER-AXLETREE (TMS)] [numeric](38, 6) NULL,
	[CARTON (Price)] [numeric](38, 6) NULL,
	[ULTRASONIC MACHINE (TMS)] [numeric](38, 6) NULL,
	[RENTAL MACHINE (Price)] [numeric](38, 6) NULL,
	[S-HOT PRESS(SEWING) (TMS)] [numeric](38, 6) NULL,
	[TTL_3C EQUIPMENT (Price)] [numeric](38, 6) NULL,
	[TTL_AE RING-KNIFE (CPU)] [numeric](38, 6) NULL,
	[TTL_AE RING-ULTRASONIC (CPU)] [numeric](38, 6) NULL,
	[TTL_AT (HAND) (CPU)] [numeric](38, 6) NULL,
	[TTL_AT (MACHINE) (CPU)] [numeric](38, 6) NULL,
	[TTL_AUTO BELT LOOPER (CPU)] [numeric](38, 6) NULL,
	[TTL_AUTO POCKET WELT (CPU)] [numeric](38, 6) NULL,
	[TTL_AUTO-TEMPLATE (CPU)] [numeric](38, 6) NULL,
	[TTL_AUTO-TEMPLATE QT (CPU)] [numeric](38, 6) NULL,
	[TTL_B-HOT PRESS(BONDING) (CPU)] [numeric](38, 6) NULL,
	[TTL_B-HOT PRESS(SUB-PRT) (CPU)] [numeric](38, 6) NULL,
	[TTL_BH-TWICE FOR PLACKET (CPU)] [numeric](38, 6) NULL,
	[TTL_BH-TWICE FOR WB (CPU)] [numeric](38, 6) NULL,
	[TTL_BLINDSTITCH (CPU)] [numeric](38, 6) NULL,
	[TTL_BONDING (HAND) (CPU)] [numeric](38, 6) NULL,
	[TTL_BONDING (MACHINE) (CPU)] [numeric](38, 6) NULL,
	[TTL_CARTON (Price)] [numeric](38, 6) NULL,
	[TTL_CHEMICAL (Price)] [numeric](38, 6) NULL,
	[TTL_COVERSTITCH CYLINDER (CPU)] [numeric](38, 6) NULL,
	[TTL_COVERSTITCH L-CUTTER (CPU)] [numeric](38, 6) NULL,
	[TTL_CUTTING (CPU)] [numeric](38, 6) NULL,
	[TTL_CUTTING TAPE (Price)] [numeric](38, 6) NULL,
	[TTL_D-CHAIN ZIG ZAG (CPU)] [numeric](38, 6) NULL,
	[TTL_DIE CUT (CPU)] [numeric](38, 6) NULL,
	[TTL_DIE-CUT (CPU)] [numeric](38, 6) NULL,
	[TTL_DOWN (CPU)] [numeric](38, 6) NULL,
	[TTL_DOWN FILLING (CPU)] [numeric](38, 6) NULL,
	[TTL_EM/DEBOSS (I/H) (CPU)] [numeric](38, 6) NULL,
	[TTL_EM/DEBOSS (MOLD) (Price)] [numeric](38, 6) NULL,
	[TTL_EMB_THREAD (Price)] [numeric](38, 6) NULL,
	[TTL_EMBOSS/DEBOSS (PCS)] [numeric](38, 6) NULL,
	[TTL_EMBOSS/DEBOSS (Price)] [numeric](38, 6) NULL,
	[TTL_EMBROIDERY (Price)] [numeric](38, 6) NULL,
	[TTL_EMBROIDERY (STITCH in thousands)] [numeric](38, 6) NULL,
	[TTL_EMBROIDERY EYELET (CPU)] [numeric](38, 6) NULL,
	[TTL_EMBROIDERY TMS (CPU)] [numeric](38, 6) NULL,
	[TTL_EYEBUTTON (CPU)] [numeric](38, 6) NULL,
	[TTL_FARM OUT QUILTING (PCS)] [numeric](38, 6) NULL,
	[TTL_FARM OUT QUILTING (Price)] [numeric](38, 6) NULL,
	[TTL_FEEDOFARM (CPU)] [numeric](38, 6) NULL,
	[TTL_FUSIBLE (CPU)] [numeric](38, 6) NULL,
	[TTL_GARMENT DYE (PCS)] [numeric](38, 6) NULL,
	[TTL_GARMENT DYE (Price)] [numeric](38, 6) NULL,
	[TTL_GENERAL AFFAIR (Price)] [numeric](38, 6) NULL,
	[TTL_GMT WASH (PCS)] [numeric](38, 6) NULL,
	[TTL_GMT WASH (Price)] [numeric](38, 6) NULL,
	[TTL_HEAT SET PLEAT (PCS)] [numeric](38, 6) NULL,
	[TTL_HEAT SET PLEAT (Price)] [numeric](38, 6) NULL,
	[TTL_HEAT TRANSFER (CPU)] [numeric](38, 6) NULL,
	[TTL_HEAT TRANSFER (PANEL)] [numeric](38, 6) NULL,
	[TTL_INDIRECT MANPOWER (CPU)] [numeric](38, 6) NULL,
	[TTL_INSPECTION (CPU)] [numeric](38, 6) NULL,
	[TTL_INTENSIVE MACHINE (CPU)] [numeric](38, 6) NULL,
	[TTL_JOKERTAG (CPU)] [numeric](38, 6) NULL,
	[TTL_LASER (CPU)] [numeric](38, 6) NULL,
	[TTL_LASER-AXLETREE (CPU)] [numeric](38, 6) NULL,
	[TTL_LASER-GALVANOMETER (CPU)] [numeric](38, 6) NULL,
	[TTL_MAINTENANCE (Price)] [numeric](38, 6) NULL,
	[TTL_PACKING (CPU)] [numeric](38, 6) NULL,
	[TTL_PAD PRINTING (Price)] [numeric](38, 6) NULL,
	[TTL_POCKET WELT (Price)] [numeric](38, 6) NULL,
	[TTL_POLYBAG (Price)] [numeric](38, 6) NULL,
	[TTL_PRESSING (CPU)] [numeric](38, 6) NULL,
	[TTL_PRINTING (PCS)] [numeric](38, 6) NULL,
	[TTL_PRINTING (Price)] [numeric](38, 6) NULL,
	[TTL_PRINTING PPU (PPU)] [numeric](38, 6) NULL,
	[TTL_QUILTING (Price)] [numeric](38, 6) NULL,
	[TTL_QUILTING(HAND) (CPU)] [numeric](38, 6) NULL,
	[TTL_REAL FLATSEAM (CPU)] [numeric](38, 6) NULL,
	[TTL_RECOAT GARMENT (Price)] [numeric](38, 6) NULL,
	[TTL_RENTAL MACHINE (Price)] [numeric](38, 6) NULL,
	[TTL_REPAIR GARMENT (Price)] [numeric](38, 6) NULL,
	[TTL_ROLLER SUBLIMATION (CPU)] [numeric](38, 6) NULL,
	[TTL_SEAM TAPING MACHINE (CPU)] [numeric](38, 6) NULL,
	[TTL_SEAMSEAL (CPU)] [numeric](38, 6) NULL,
	[TTL_SEWING (CPU)] [numeric](38, 6) NULL,
	[TTL_SHIPPING (Price)] [numeric](38, 6) NULL,
	[TTL_S-HOT PRESS(BONDING) (CPU)] [numeric](38, 6) NULL,
	[TTL_S-HOT PRESS(HT) (CPU)] [numeric](38, 6) NULL,
	[TTL_S-HOT PRESS(SEWING) (CPU)] [numeric](38, 6) NULL,
	[TTL_SMALL HOT PRESS-LONG (CPU)] [numeric](38, 6) NULL,
	[TTL_SP_THREAD (Price)] [numeric](38, 6) NULL,
	[TTL_STATIONERY (Price)] [numeric](38, 6) NULL,
	[TTL_SUBLIMATION PRINT (CPU)] [numeric](38, 6) NULL,
	[TTL_SUBLIMATION ROLLER (CPU)] [numeric](38, 6) NULL,
	[TTL_ULTRASONIC (CPU)] [numeric](38, 6) NULL,
	[TTL_ULTRASONIC MACHINE (CPU)] [numeric](38, 6) NULL,
	[TTL_ULTRASONIC-ELASTIC (CPU)] [numeric](38, 6) NULL,
	[TTL_ULTRASONIC-LABEL ASM (CPU)] [numeric](38, 6) NULL,
	[TTL_ULTRASONIC-TAPE CUT (CPU)] [numeric](38, 6) NULL,
	[TTL_VELCRO MACHINE (CPU)] [numeric](38, 6) NULL,
	[TTL_VELCROED M/C (CPU)] [numeric](38, 6) NULL,
	[TTL_WELTED M/C (CPU)] [numeric](38, 6) NULL,
	[TTL_ZIG ZAG (CPU)] [numeric](38, 6) NULL,
	[Subcon In TypeID] [varchar](2) NOT NULL,
	[Article] [varchar](1000) NULL,
	[Ukey] [bigint] IDENTITY(1,1) NOT NULL,
	[Delay Supp by Ref] [varchar](2000) NOT NULL,
	[SCHD L/ETA(SP excl. Repl.)] [date] NULL,
 CONSTRAINT [T_OrderList_PK] PRIMARY KEY CLUSTERED 
(
	[SPNO] ASC,
	[FromType] ASC,
	[Factory] ASC,
	[Subcon In TypeID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[T_OrderList] ADD  CONSTRAINT [T_OrderList_Factory]  DEFAULT ('') FOR [Factory]
GO

ALTER TABLE [dbo].[T_OrderList] ADD  CONSTRAINT [T_OrderList_SPNo]  DEFAULT ('') FOR [SPNO]
GO

ALTER TABLE [dbo].[T_OrderList] ADD  CONSTRAINT [T_OrderList_FromType]  DEFAULT ('') FOR [FromType]
GO

ALTER TABLE [dbo].[T_OrderList] ADD  DEFAULT ('') FOR [Subcon In TypeID]
GO


