CREATE TABLE [dbo].[T_SDP](
	[Country] [varchar](30) NULL,
	[KPIGroup] [varchar](8) NULL,
	[Factory] [varchar](8) NULL,
	[SPNO] [varchar](13) NULL,
	[StyleID] [varchar](15) NULL,
	[Seq] [varchar](3) NULL,
	[Brand] [varchar](8) NULL,
	[BuyerDelivery] [date] NULL,
	[FactoryKPI] [date] NULL,
	[Extension] [date] NULL,
	[DeliveryByShipMode] [varchar](10) NULL,
	[OrderQty] [numeric](6, 0) NULL,
	[OnTimeQty] [numeric](6, 0) NULL,
	[FailQty] [numeric](6, 0) NULL,
	[PullOutDate] [date] NULL,
	[ShipMode] [varchar](10) NULL,
	[P] [numeric](2, 0) NULL,
	[GarmentComplete] [varchar](1) NULL,
	[ReasonID] [varchar](5) NULL,
	[OrderReason] [varchar](500) NULL,
	[LastSewingOutputDate] [date] NULL,
	[LastCartonReceivedDate] [date] NULL,
	[Handle] [varchar](200) NULL,
	[SMR] [varchar](200) NULL,
	[POHandle] [varchar](200) NULL,
	[POSMR] [varchar](200) NULL,
	[OrderType] [varchar](20) NULL,
	[DevSample] [varchar](1) NULL,
	[SewingQty] [numeric](6, 0) NULL,
	[FOCQty] [numeric](6, 0) NULL,
	[PartialShipment] [varchar](1) NULL,
	[OutstandingReason] [varchar](500) NULL,
	[ReasonRemark] [nvarchar](max) NULL,
	[TransferBIDate] [datetime] NULL,
	[Ukey] [bigint] NOT NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO


