CREATE TABLE [dbo].[﻿T_ArtworkComparison]
(
    [Source] [varchar](8) NULL,
    [ID] [varchar](13) NULL,
    [BrandID] [varchar](8) NULL,
    [StyleID] [varchar](15) NULL,
    [SeasonID] [varchar](10) NULL,
    [FactoryID] [varchar](8) NULL,
    [BuyerDelivery] [date] NULL,
    [SCIDelivery] [date] NULL,
    [CDCodeID] [varchar](6) NULL,
    [Category] [varchar](15) NULL,
    [SMR] [nvarchar](58) NULL,
    [MR] [nvarchar](58) NULL,
    [Region] [varchar](2) NULL,
    [MDivisionID] [varchar](8) NULL,
    [ProgramID] [varchar](12) NULL,
    [StyleUkey] [bigint] NULL,
    [COO] [nvarchar](30) NULL,
    [Artwork] [varchar](20) NULL,
    [Amount] [numeric](18, 4) NULL,
    [ProductType] [nvarchar](500) NULL,
    [FabricType] [nvarchar](500) NULL,
    [Construction] [nvarchar](50) NULL,
    [CPU] [numeric](8, 3) NULL,
    [StyleName] [nvarchar](50) NULL,
    [TransferBIDate] [datetime] NULL,
    [Ukey] [bigint] NOT NULL
)