CREATE TABLE [dbo].[BundleReplacement] (
    [ID]              VARCHAR (13)  NOT NULL,
    [POID]            VARCHAR (13)  NOT NULL,
    [MDivisionid]     VARCHAR (8)   NOT NULL,
    [Sizecode]        VARCHAR (100) NOT NULL,
    [Colorid]         VARCHAR (6)   NOT NULL,
    [Article]         VARCHAR (8)   NOT NULL,
    [PatternPanel]    VARCHAR (2)   NOT NULL,
    [Cutno]           NUMERIC (6)   NULL,
    [Cdate]           DATE          NULL,
    [Orderid]         VARCHAR (13)  NOT NULL,
    [Sewinglineid]    VARCHAR (2)   NOT NULL,
    [Item]            VARCHAR (20)  NULL,
    [SewingCell]      VARCHAR (2)   NOT NULL,
    [Ratio]           VARCHAR (100) NULL,
    [Startno]         NUMERIC (5)   NULL,
    [Qty]             NUMERIC (2)   NULL,
    [PrintDate]       DATETIME      NULL,
    [AllPart]         NUMERIC (5)   NULL,
    [OriginBundleNo]  VARCHAR (10)  NULL,
    [AddName]         VARCHAR (10)  NULL,
    [AddDate]         DATETIME      NULL,
    [EditName]        VARCHAR (10)  NULL,
    [EditDate]        DATETIME      NULL,
    [oldid]           VARCHAR (13)  NULL,
    [FabricPanelCode] VARCHAR (2)   NULL,
    [Remake]          BIT           NOT NULL,
    CONSTRAINT [PK_BundleReplacement] PRIMARY KEY CLUSTERED ([ID] ASC)
);

