CREATE TABLE [dbo].[CTNHauling]
(
	[Id] BIGINT NOT NULL PRIMARY KEY IDENTITY, 
    [HaulingDate] DATETIME NOT NULL, 
    [MDivisionID] VARCHAR(8) NOT NULL DEFAULT '', 
    [OrderID] VARCHAR(13) NOT NULL DEFAULT '', 
    [PackingListID] VARCHAR(13) NOT NULL DEFAULT '', 
    [CTNStartNo] VARCHAR(6) NOT NULL DEFAULT '', 
    [SCICtnNo] VARCHAR(16) NOT NULL DEFAULT '', 
    [AddName] VARCHAR(10) NOT NULL DEFAULT '', 
    [AddDate] DATETIME NOT NULL DEFAULT GetDate()
)
