CREATE TABLE [dbo].[DailyAccuCPULoading_Detail]
(
	 [DailyAccuCPULoadingUkey]		bigint				NOT NULL DEFAULT ((0))
	,[Date]							varchar(5)			NOT NULL DEFAULT ((''))
	,[WeekDay]						varchar(3)			NOT NULL DEFAULT ((''))
	,[DailyCPULoading]				decimal(10,3)		NOT NULL DEFAULT ((0))
	,[NewTarget]					int					NOT NULL DEFAULT ((''))
	,[ActCPUPerformed]				decimal(8,3)		NOT NULL DEFAULT ((0))
	,[DailyCPUVarience]				decimal(10,3)		NOT NULL DEFAULT ((0))
	,[AccuLoading]					decimal(10,3)		NOT NULL DEFAULT ((0))
	,[AccuActCPUPerformed]			decimal(10,3)		NOT NULL DEFAULT ((0))
	,[AccuCPUVariance]				decimal(10,3)		NOT NULL DEFAULT ((0))
	,[LeftWorkDays]					int					NOT NULL DEFAULT ((0))
	,[AvgWorkhours]					decimal(8,2)		NOT NULL DEFAULT ((0))
	,[PPH]							decimal(8,2)		NOT NULL DEFAULT ((0))
	,[Direct]						int					NOT NULL DEFAULT ((0))
	,[Active]						int					NOT NULL DEFAULT ((0))
	,[VPH]							decimal(8,2)		NOT NULL DEFAULT ((0))
	,[ManpowerRatio]				decimal(8,2)		NOT NULL DEFAULT ((0))
	,[LineNo]						int					NOT NULL DEFAULT ((0))
	,[LineManpower]					int					NOT NULL DEFAULT ((0))
	,[GPH]							decimal(8,2)		NOT NULL DEFAULT ((0))
	,[SPH]							decimal(8,2)		NOT NULL DEFAULT ((0))
)
