CREATE TABLE [dbo].[DDTable] (
    [ID]      VARCHAR (80)  CONSTRAINT [DF_DDTable_ID] DEFAULT ('') NOT NULL,
    [Name950] NVARCHAR (50) CONSTRAINT [DF_DDTable_Name950] DEFAULT ('') NULL,
    [Name000] NVARCHAR (50) CONSTRAINT [DF_DDTable_Name000] DEFAULT ('') NULL,
    CONSTRAINT [PK_DDTable] PRIMARY KEY CLUSTERED ([ID] ASC)
);

