CREATE TABLE [dbo].[ICR]
(
	[Id] VARCHAR(13) NOT NULL PRIMARY KEY DEFAULT (''), 
    [Responsible] VARCHAR NOT NULL DEFAULT (''), 
    [Department] NVARCHAR(40) NOT NULL DEFAULT (''), 
    [OrderID] VARCHAR(13) NOT NULL DEFAULT (''), 
    [Status] VARCHAR(15) NOT NULL DEFAULT (''), 
    [StatusUpdate] DATETIME NULL, 
    [Handle] VARCHAR(10) NOT NULL DEFAULT (''), 
    [SMR] VARCHAR(10) NOT NULL DEFAULT (''), 
    [ReceiveHandle] VARCHAR(10) NOT NULL DEFAULT (''), 
    [CFMDate] DATE NULL, 
    [CFMHandle] VARCHAR(10) NOT NULL DEFAULT (''), 
    [DutyHandle] VARCHAR(10) NOT NULL DEFAULT (''), 
    [DutySMR] VARCHAR(10) NOT NULL DEFAULT (''), 
    [DutyManager] VARCHAR(10) NOT NULL DEFAULT (''), 
    [unpayable] BIT NOT NULL DEFAULT ((0)), 
    [Deadline] DATE NULL, 
    [DutyStatus] VARCHAR(15) NOT NULL DEFAULT (''), 
    [DutyStatusUpdate] DATETIME NULL, 
    [RMtlAmt] NUMERIC(11, 2) NOT NULL DEFAULT ((0)), 
    [EstFreight] NUMERIC(11, 2) NOT NULL DEFAULT ((0)), 
    [ActFreight] NUMERIC(10, 2) NOT NULL DEFAULT ((0)), 
    [OtherAmt] NUMERIC(10, 2) NOT NULL DEFAULT ((0)), 
    [RMtlAmtUSD] NUMERIC(10, 2) NOT NULL DEFAULT ((0)), 
    [EstFreightUSD] NUMERIC(10, 2) NOT NULL DEFAULT ((0)), 
    [ActFreightUSD] NUMERIC(10, 2) NOT NULL DEFAULT ((0)), 
    [OtherAmtUSD] NUMERIC(10, 2) NOT NULL DEFAULT ((0)), 
    [Exchange] NUMERIC(10, 2) NOT NULL DEFAULT ((0)), 
    [IrregularPOCostID] VARCHAR(5) NOT NULL DEFAULT (''), 
    [Description] NVARCHAR(MAX) NOT NULL DEFAULT (''), 
    [Suggestion] NVARCHAR(MAX) NOT NULL DEFAULT (''), 
    [Remark] NVARCHAR(MAX) NOT NULL DEFAULT (''), 
    [AddName] VARCHAR(10) NOT NULL DEFAULT (''), 
    [AddDate] DATETIME NULL, 
    [EditName] VARCHAR(10) NOT NULL DEFAULT (''), 
    [EditDate] DATETIME2 NULL , 
    [VoucherID] VARCHAR(16) NOT NULL DEFAULT (''), 
    [VoucherDate] DATE NULL
)
