CREATE TABLE [dbo].[OrderChangeApplication] (
    [ID]                 VARCHAR (13)   NOT NULL,
    [ReasonID]           VARCHAR (5)    NULL,
    [OrderID]            VARCHAR (13)   NULL,
    [Status]             VARCHAR (15)   NULL,
    [AddName]            VARCHAR (10)   NULL,
    [AddDate]            DATETIME       NULL,
    [EditName]           VARCHAR (10)   NULL,
    [EditDate]           DATETIME       NULL,
    [ToOrderID]          VARCHAR (13)   NULL,
    [NeedProduction]     BIT            CONSTRAINT [DF_OrderChangeApplication_NeedProduction] DEFAULT ((0)) NOT NULL,
    [OldQty]             NUMERIC (6)    CONSTRAINT [DF_OrderChangeApplication_OldQty] DEFAULT ((0)) NOT NULL,
    [ResponsibleFtyNo]   VARCHAR (8)    NULL,
    [RatioFty]           NUMERIC (5, 2) CONSTRAINT [DF_OrderChangeApplication_RatioFty] DEFAULT ((0)) NOT NULL,
    [RatioSubcon]        NUMERIC (5, 2) CONSTRAINT [DF_OrderChangeApplication_RatioSubcon] DEFAULT ((0)) NOT NULL,
    [RatioSCI]           NUMERIC (5, 2) CONSTRAINT [DF_OrderChangeApplication_RatioSCI] DEFAULT ((0)) NOT NULL,
    [RatioSupp]          NUMERIC (5, 2) CONSTRAINT [DF_OrderChangeApplication_RatioSupp] DEFAULT ((0)) NOT NULL,
    [RatioBuyer]         NUMERIC (5, 2) CONSTRAINT [DF_OrderChangeApplication_RatioBuyer] DEFAULT ((0)) NOT NULL,
    [ResponsibleFty]     BIT            CONSTRAINT [DF_OrderChangeApplication_ResponsibleFty] DEFAULT ((0)) NOT NULL,
    [ResponsibleSubcon]  BIT            CONSTRAINT [DF_OrderChangeApplication_ResponsibleSubcon] DEFAULT ((0)) NOT NULL,
    [ResponsibleSCI]     BIT            CONSTRAINT [DF_OrderChangeApplication_ResponsibleSCI] DEFAULT ((0)) NOT NULL,
    [ResponsibleSupp]    BIT            CONSTRAINT [DF_OrderChangeApplication_ResponsibleSupp] DEFAULT ((0)) NOT NULL,
    [ResponsibleBuyer]   BIT            CONSTRAINT [DF_OrderChangeApplication_ResponsibleBuyer] DEFAULT ((0)) NOT NULL,
    [FactoryICRNo]       NVARCHAR (13)  NULL,
    [SubconDBCNo]        NVARCHAR (13)  NULL,
    [SubConName]         NVARCHAR (20)  NULL,
    [SCIICRNo]           NVARCHAR (13)  NULL,
    [SCIICRDepartment]   NVARCHAR (40)  NULL,
    [SuppDBCNo]          NVARCHAR (13)  NULL,
    [BuyerDBCNo]         NVARCHAR (13)  NULL,
    [BuyerDBCDepartment] NVARCHAR (40)  NULL,
    [BuyerICRNo]         NVARCHAR (13)  NULL,
    [SubconDBCRemark]    NVARCHAR (MAX) NULL,
    [SCIICRRemark]       NVARCHAR (MAX) NULL,
    [SuppDBCRemark]      NVARCHAR (MAX) NULL,
    [BuyerDBCRemark]     NVARCHAR (MAX) NULL,
    [BuyerICRRemark]     NVARCHAR (MAX) NULL,
    [FtyDesc]            NVARCHAR (50)  NULL,
    [MRComment]          NVARCHAR (MAX) NULL,
    [Remark]             NVARCHAR (MAX) NULL,
    [BuyerRemark]        NVARCHAR (MAX) NULL,
    CONSTRAINT [PK_OrderChangeApplication] PRIMARY KEY CLUSTERED ([ID] ASC)
);



