CREATE TABLE [dbo].[PackErrCFM]
(
	[ID] BIGINT IDENTITY (1, 1) NOT NULL, 
    [CFMDate] DATE NULL, 
    [MDivisionID] VARCHAR(8) CONSTRAINT [DF_PackErrCFM_MDivisionID] DEFAULT ('') NULL, 
    [OrderID] VARCHAR(13) CONSTRAINT [DF_PackErrCFM_OrderID] DEFAULT ('') NULL, 
    [PackingListID] VARCHAR(13) CONSTRAINT [DF_PackErrCFM_PackingListID] DEFAULT ('') NULL, 
    [CTNStartNo] VARCHAR(6) CONSTRAINT [DF_PackErrCFM_CTNStartNo] DEFAULT ('') NULL,  
    [AddName] VARCHAR(10) CONSTRAINT [DF_PackErrCFM_AddName] DEFAULT ('') NULL,  
    [AddDate] DATETIME NULL, 
    [SCICtnNo] VARCHAR(16) CONSTRAINT [DF_PackErrCFM_SCICtnNo] DEFAULT ('') NOT NULL,  
    CONSTRAINT [PK_PackErrCFM] PRIMARY KEY CLUSTERED ([ID] ASC)
)
