CREATE TABLE [dbo].[Query] (
    [Ukey_Old]          CHAR (10)       NULL,
    [Ukey]              BIGINT          NOT NULL,
    [Type]              CHAR (1)        NOT NULL,
    [Refno]             CHAR (36)       NOT NULL,
    [Picture1]          NVARCHAR (60)   NULL,
    [Picture2]          NVARCHAR (40)   NULL,
    [Junk]              BIT             NULL,
    [SuppID]            CHAR (6)        NOT NULL,
    [MachineGroupID]    CHAR (2)        NOT NULL,
    [MachineBrandID]    CHAR (10)       NULL,
    [Model]             NVARCHAR (50)   NULL,
    [PartNo]            CHAR (20)       NOT NULL,
    [UnitID]            CHAR (8)        NOT NULL,
    [PoUnitID]          CHAR (8)        NOT NULL,
    [BatchQty]          DECIMAL (4)     NOT NULL,
    [Price]             DECIMAL (12, 4) NOT NULL,
    [CurrencyID]        CHAR (3)        NOT NULL,
    [Leadtime]          DECIMAL (3)     NULL,
    [Formula]           DECIMAL (7, 2)  NULL,
    [Fix]               BIT             NULL,
    [Description]       NVARCHAR (100)  NOT NULL,
    [DescriptionDetail] NTEXT           NULL,
    [Remark]            NVARCHAR (60)   NULL,
    [Origin]            CHAR (2)        NULL,
    [IsMachine]         BIT             NULL,
    [IsAsset]           BIT             NULL,
    [AccountID]         CHAR (8)        NULL,
    [AddName]           CHAR (10)       NULL,
    [AddDate]           DATETIME2 (3)   NULL,
    [EditName]          CHAR (10)       NULL,
    [EditDate]          DATETIME2 (3)   NULL
);

