CREATE TABLE [dbo].[System] (
    [Mailserver]                          VARCHAR (60)   CONSTRAINT [DF_System_Mailserver] DEFAULT ('') NOT NULL,
    [Sendfrom]                            VARCHAR (40)   CONSTRAINT [DF_System_Sendfrom] DEFAULT ('') NOT NULL,
    [EmailID]                             VARCHAR (40)   CONSTRAINT [DF_System_EmailID] DEFAULT ('') NOT NULL,
    [EmailPwd]                            VARCHAR (20)   CONSTRAINT [DF_System_EmailPwd] DEFAULT ('') NOT NULL,
    [PicPath]                             VARCHAR (80)   CONSTRAINT [DF_System_PicPath] DEFAULT ('') NOT NULL,
    [StdTMS]                              INT            CONSTRAINT [DF_System_StdTMS] DEFAULT ((0)) NOT NULL,
    [ClipPath]                            VARCHAR (80)   CONSTRAINT [DF_System_ClipPath] DEFAULT ('') NOT NULL,
    [FtpIP]                               VARCHAR (36)   CONSTRAINT [DF_System_FtpIP] DEFAULT ('') NOT NULL,
    [FtpID]                               VARCHAR (10)   CONSTRAINT [DF_System_FtpID] DEFAULT ('') NOT NULL,
    [FtpPwd]                              VARCHAR (36)   CONSTRAINT [DF_System_FtpPwd] DEFAULT ('') NOT NULL,
    [SewLock]                             DATE           NULL,
    [SampleRate]                          TINYINT        CONSTRAINT [DF_System_SampleRate] DEFAULT ((0)) NOT NULL,
    [PullLock]                            DATE           NULL,
    [RgCode]                              VARCHAR (3)    CONSTRAINT [DF_System_RgCode] DEFAULT ('') NOT NULL,
    [ImportDataPath]                      VARCHAR (60)   CONSTRAINT [DF_System_ImportDataPath] DEFAULT ('') NOT NULL,
    [ImportDataFileName]                  VARCHAR (60)   CONSTRAINT [DF_System_ImportDataFileName] DEFAULT ('') NOT NULL,
    [ExportDataPath]                      VARCHAR (60)   CONSTRAINT [DF_System_ExportDataPath] DEFAULT ('') NOT NULL,
    [CurrencyID]                          VARCHAR (4)    CONSTRAINT [DF_System_CurrencyID] DEFAULT ('') NOT NULL,
    [USDRate]                             DECIMAL (9, 4) CONSTRAINT [DF_System_USDRate] DEFAULT ((0)) NOT NULL,
    [POApproveName]                       VARCHAR (10)   CONSTRAINT [DF_System_POApproveName] DEFAULT ('') NOT NULL,
    [POApproveDay]                        TINYINT        CONSTRAINT [DF_System_POApproveDay] DEFAULT ((0)) NOT NULL,
    [CutDay]                              TINYINT        CONSTRAINT [DF_System_CutDay] DEFAULT ((0)) NOT NULL,
    [AccountKeyword]                      VARCHAR (1)    CONSTRAINT [DF_System_AccountKeyword] DEFAULT ('') NOT NULL,
    [ReadyDay]                            TINYINT        CONSTRAINT [DF_System_ReadyDay] DEFAULT ((0)) NOT NULL,
    [VNMultiple]                          DECIMAL (4, 2) CONSTRAINT [DF_System_VNMultiple] DEFAULT ((0)) NOT NULL,
    [MtlLeadTime]                         TINYINT        CONSTRAINT [DF_System_MtlLeadTime] DEFAULT ((0)) NOT NULL,
    [ExchangeID]                          VARCHAR (2)    CONSTRAINT [DF_System_ExchangeID] DEFAULT ('') NOT NULL,
    [RFIDServerName]                      VARCHAR (20)   CONSTRAINT [DF_System_RFIDServerName] DEFAULT ('') NOT NULL,
    [RFIDDatabaseName]                    VARCHAR (20)   CONSTRAINT [DF_System_RFIDDatabaseName] DEFAULT ('') NOT NULL,
    [RFIDLoginId]                         VARCHAR (20)   CONSTRAINT [DF_System_RFIDLoginId] DEFAULT ('') NOT NULL,
    [RFIDLoginPwd]                        VARCHAR (20)   CONSTRAINT [DF_System_RFIDLoginPwd] DEFAULT ('') NOT NULL,
    [RFIDTable]                           VARCHAR (20)   CONSTRAINT [DF_System_RFIDTable] DEFAULT ('') NOT NULL,
    [ProphetSingleSizeDeduct]             DECIMAL (3)    CONSTRAINT [DF_System_ProphetSingleSizeDeduct] DEFAULT ((0)) NOT NULL,
    [PrintingSuppID]                      VARCHAR (8)    CONSTRAINT [DF_System_PrintingSuppID] DEFAULT ('') NOT NULL,
    [QCMachineDelayTime]                  DECIMAL (2, 1) CONSTRAINT [DF_System_QCMachineDelayTime] DEFAULT ((0)) NOT NULL,
    [APSLoginId]                          VARCHAR (15)   CONSTRAINT [DF_System_APSLoginId] DEFAULT ('') NOT NULL,
    [APSLoginPwd]                         VARCHAR (15)   CONSTRAINT [DF_System_APSLoginPwd] DEFAULT ('') NOT NULL,
    [SQLServerName]                       VARCHAR (130)  CONSTRAINT [DF_System_SQLServerName] DEFAULT ('') NOT NULL,
    [APSDatabaseName]                     VARCHAR (15)   CONSTRAINT [DF_System_APSDatabaseName] DEFAULT ('') NOT NULL,
    [UseAutoScanPack]                     BIT            CONSTRAINT [DF_System_UseAutoScanPack] DEFAULT ((0)) NOT NULL,
    [MtlAutoLock]                         BIT            CONSTRAINT [DF_System_MtlAutoLock] DEFAULT ((0)) NOT NULL,
    [InspAutoLockAcc]                     BIT            DEFAULT ((0)) NOT NULL,
    [RFIDMiddlewareInRFIDServer]          BIT            DEFAULT ((0)) NOT NULL,
    [ShippingMarkPath]                    VARCHAR (80)   CONSTRAINT [DF_System_ShippingMarkPath] DEFAULT ('') NOT NULL,
    [StyleSketch]                         VARCHAR (80)   CONSTRAINT [DF_System_StyleSketch] DEFAULT ('') NOT NULL,
    [ARKServerName]                       VARCHAR (20)   CONSTRAINT [DF_System_ARKServerName] DEFAULT ('') NOT NULL,
    [ARKDatabaseName]                     VARCHAR (20)   CONSTRAINT [DF_System_ARKDatabaseName] DEFAULT ('') NOT NULL,
    [ARKLoginId]                          VARCHAR (20)   CONSTRAINT [DF_System_ARKLoginId] DEFAULT ('') NOT NULL,
    [ARKLoginPwd]                         VARCHAR (20)   CONSTRAINT [DF_System_ARKLoginPwd] DEFAULT ('') NOT NULL,
    [MarkerInputPath]                     NVARCHAR (80)  CONSTRAINT [DF_System_MarkerInputPath] DEFAULT ('') NOT NULL,
    [MarkerOutputPath]                    NVARCHAR (80)  CONSTRAINT [DF_System_MarkerOutputPath] DEFAULT ('') NOT NULL,
    [ReplacementReport]                   VARCHAR (80)   CONSTRAINT [DF_System_ReplacementReport] DEFAULT ('') NOT NULL,
    [CuttingP10mustCutRef]                BIT            DEFAULT ((0)) NOT NULL,
    [Automation]                          BIT            DEFAULT ((0)) NOT NULL,
    [AutomationAutoRunTime]               TINYINT        CONSTRAINT [DF_System_AutomationAutoRunTime] DEFAULT ((0)) NOT NULL,
    [CanReviseDailyLockData]              BIT            DEFAULT ((0)) NOT NULL,
    [AutoGenerateByTone]                  BIT            CONSTRAINT [DF_System_AutoGenerateByTone] DEFAULT ((0)) NOT NULL,
    [MiscPOApproveName]                   VARCHAR (10)   CONSTRAINT [DF_System_MiscPOApproveName] DEFAULT ('') NOT NULL,
    [MiscPOApproveDay]                    TINYINT        CONSTRAINT [DF_System_MiscPOApproveDay] DEFAULT ((0)) NOT NULL,
    [QMSAutoAdjustMtl]                    BIT            DEFAULT ((0)) NOT NULL,
    [ShippingMarkTemplatePath]            VARCHAR (80)   NOT NULL,
    [WIP_FollowCutOutput]                 BIT            CONSTRAINT [DF_System_WIP_FollowCutOutput] DEFAULT ((0)) NOT NULL,
    [NoRestrictOrdersDelivery]            BIT            CONSTRAINT [DF_System_NoRestrictOrdersDelivery] DEFAULT ((0)) NOT NULL,
    [WIP_ByShell]                         BIT            CONSTRAINT [DF_System_WIP_ByShell] DEFAULT ((0)) NOT NULL,
    [RFCardEraseBeforePrinting]           BIT            DEFAULT ((0)) NOT NULL,
    [SewlineAvgCPU]                       INT            CONSTRAINT [DF_System_SewlineAvgCPU] DEFAULT ((0)) NOT NULL,
    [SmallLogoCM]                         DECIMAL (5, 2) CONSTRAINT [DF_System_SmallLogoCM] DEFAULT ((0)) NOT NULL,
    [CheckRFIDCardDuplicateByWebservice]  BIT            CONSTRAINT [DF_System_CheckRFIDCardDuplicateByWebservice] DEFAULT ((0)) NOT NULL,
    [IsCombineSubProcess]                 BIT            CONSTRAINT [DF_System_IsCombineSubProcess] DEFAULT ((0)) NOT NULL,
    [IsNoneShellNoCreateAllParts]         BIT            CONSTRAINT [DF_System_IsNoneShellNoCreateAllParts] DEFAULT ((0)) NOT NULL,
    [Region]                              VARCHAR (2)    CONSTRAINT [DF_System_Region] DEFAULT ('') NOT NULL,
    [FinalInspection_CTNMoistureStandard] NUMERIC (5, 2) CONSTRAINT [DF_System_FinalInspection_CTNMoistureStandard] DEFAULT ((0)) NOT NULL,
    [StyleFDFilePath]                     VARCHAR (80)   DEFAULT ('') NOT NULL,
    [StyleRRLRPath]                       VARCHAR (80)   DEFAULT ('') NOT NULL,
    [WH_MtlTransChkLocation]              BIT            DEFAULT ((0)) NOT NULL,
    [CartonTransferToSisterFty]           BIT            CONSTRAINT [DF_System_CartonTransferToSisterFty] DEFAULT ((0)) NOT NULL,
    [MailServerPort]                      SMALLINT       CONSTRAINT [DF_System_MailServerPort] DEFAULT ((0)) NOT NULL,
    [PMS_FabricQRCode_LabelSize]          VARCHAR (5)    CONSTRAINT [DF_System_PMS_FabricQRCode_LabelSize] DEFAULT ('5X5') NOT NULL,
    [PDA_FabricQRCode_LabelSize]          VARCHAR (5)    CONSTRAINT [DF_System_PDA_FabricQRCode_LabelSize] DEFAULT ('5X5') NOT NULL,
    [HandoverATPath]                      VARCHAR (80)   DEFAULT ('') NOT NULL,
    [HandoverSpecialToolsPath]            VARCHAR (80)   DEFAULT ('') NOT NULL,
    [CriticalOperationPath]               VARCHAR (80)   DEFAULT ('') NOT NULL,
    [FinalPatternPath]                    VARCHAR (80)   DEFAULT ('') NOT NULL,
    [PadPrintPath]                        VARCHAR (80)   DEFAULT ('') NOT NULL,
    [FabricPath]                          NVARCHAR (120) DEFAULT ('') NOT NULL,
    [ColorPath]                           NVARCHAR (120) DEFAULT ('') NOT NULL,
    [IsLoginCheckADAccount] [bit] NOT NULL CONSTRAINT [DF_System_IsLoginCheckADAccount]  DEFAULT ((0)),
    [NikeFactoryCode] VARCHAR(3) CONSTRAINT [DF_System_NikeFactoryCode] DEFAULT ('') NOT NULL,
    [NikeStickerPrintServer] VARCHAR(20)  CONSTRAINT [DF_System_NikeStickerPrintServer] DEFAULT ('') NOT NULL,
    [NikeStickerPrintFileFolder] VARCHAR(100)  CONSTRAINT [DF_System_NikeStickerPrintFileFolder] DEFAULT ('') NOT NULL,
    [ImportDataPathDummy] [varchar](60) NOT NULL CONSTRAINT [DF_System_ImportDataPathDummy]  DEFAULT (''),
	[ImportDataFileNameDummy] [varchar](60) NOT NULL CONSTRAINT [DF_System_ImportDataFileNameDummy]  DEFAULT (''),
	[ExportDataPathDummy] [varchar](60) NOT NULL CONSTRAINT [DF_System_ExportDataPathDummy]  DEFAULT (''),
	IEPath NVARCHAR(120) NOT NULL CONSTRAINT [DF_System_IEPath] Default '',
    [isNeedOTPFty] BIT NOT NULL DEFAULT ((0)), 
    [MercuryErrorEmailLastDate] DATE NOT NULL, 
    [FtpPortDummy] VARCHAR(4) NOT NULL DEFAULT '', 
    [FtpPort] VARCHAR(5) NOT NULL DEFAULT '', 
    [SFtpIP] VARCHAR(36) NOT NULL DEFAULT (''), 
    [SFtpPort] VARCHAR(5) NOT NULL DEFAULT (''), 
    [SFtpID] VARCHAR(20) NOT NULL DEFAULT (''), 
    [SFtpPwd] VARCHAR(36) NOT NULL DEFAULT (''), 
    [SFtpIPDummy] VARCHAR(36) NOT NULL DEFAULT (''), 
    [SFtpPortDummy] VARCHAR(5) NOT NULL DEFAULT (''), 
    [SFtpIDDummy] VARCHAR(20) NOT NULL DEFAULT (''), 
    [SFtpPwdDummy] VARCHAR(36) NOT NULL DEFAULT (''), 
    [UseCutRefToRequestFabric] TINYINT NOT NULL DEFAULT ((0)), 
    CONSTRAINT [PK_RgCode] PRIMARY KEY CLUSTERED ([RgCode] ASC)
);
go
EXEC sp_addextendedproperty @name = N'MS_Description',
    @value = N'PDA 列印布捲 QR Code 的標籤大小',
    @level0type = N'SCHEMA',
    @level0name = N'dbo',
    @level1type = N'TABLE',
    @level1name = N'System',
    @level2type = N'COLUMN',
    @level2name = N'PDA_FabricQRCode_LabelSize'
GO
EXEC sp_addextendedproperty @name = N'MS_Description',
    @value = N'放Template/Auto Template檔案的路徑',
    @level0type = N'SCHEMA',
    @level0name = N'dbo',
    @level1type = N'TABLE',
    @level1name = N'System',
    @level2type = N'COLUMN',
    @level2name = N'HandoverATPath'
GO
EXEC sp_addextendedproperty @name = N'MS_Description',
    @value = N'放Special Tools檔案的路徑',
    @level0type = N'SCHEMA',
    @level0name = N'dbo',
    @level1type = N'TABLE',
    @level1name = N'System',
    @level2type = N'COLUMN',
    @level2name = N'HandoverSpecialToolsPath'
GO
EXEC sp_addextendedproperty @name = N'MS_Description',
    @value = N'放Critical Operation檔案的路徑',
    @level0type = N'SCHEMA',
    @level0name = N'dbo',
    @level1type = N'TABLE',
    @level1name = N'System',
    @level2type = N'COLUMN',
    @level2name = N'CriticalOperationPath'
GO
EXEC sp_addextendedproperty @name = N'MS_Description',
    @value = N'放Final Pattern and Marker List檔案的路徑',
    @level0type = N'SCHEMA',
    @level0name = N'dbo',
    @level1type = N'TABLE',
    @level1name = N'System',
    @level2type = N'COLUMN',
    @level2name = N'FinalPatternPath'
GO
EXEC sp_addextendedproperty @name = N'MS_Description',
    @value = N'PadPrintLayout檔案路徑',
    @level0type = N'SCHEMA',
    @level0name = N'dbo',
    @level1type = N'TABLE',
    @level1name = N'System',
    @level2type = N'COLUMN',
    @level2name = N'PadPrintPath'
GO
EXEC sp_addextendedproperty @name = N'MS_Description',
    @value = N'是否特過WS來檢查RFID卡重複使用',
    @level0type = N'SCHEMA',
    @level0name = N'dbo',
    @level1type = N'TABLE',
    @level1name = N'System',
    @level2type = N'COLUMN',
    @level2name = N'CheckRFIDCardDuplicateByWebservice'
GO
EXEC sp_addextendedproperty @name = N'MS_Description',
    @value = N'PH 產線平均一天的 CPU',
    @level0type = N'SCHEMA',
    @level0name = N'dbo',
    @level1type = N'TABLE',
    @level1name = N'System',
    @level2type = N'COLUMN',
    @level2name = N'SewlineAvgCPU'
GO
EXEC sp_addextendedproperty @name = N'MS_Description',
    @value = N'以下判斷 smalll logo 的長度標準 (CM)',
    @level0type = N'SCHEMA',
    @level0name = N'dbo',
    @level1type = N'TABLE',
    @level1name = N'System',
    @level2type = N'COLUMN',
    @level2name = N'SmallLogoCM'
GO
EXEC sp_addextendedproperty @name = N'MS_Description',
    @value = N'是否combine subprocess產生bundle',
    @level0type = N'SCHEMA',
    @level0name = N'dbo',
    @level1type = N'TABLE',
    @level1name = N'System',
    @level2type = N'COLUMN',
    @level2name = N'IsCombineSubProcess'
GO
EXEC sp_addextendedproperty @name = N'MS_Description',
    @value = N'是否不產生AllParts',
    @level0type = N'SCHEMA',
    @level0name = N'dbo',
    @level1type = N'TABLE',
    @level1name = N'System',
    @level2type = N'COLUMN',
    @level2name = N'IsNoneShellNoCreateAllParts'
GO
EXEC sp_addextendedproperty @name = N'MS_Description',
    @value = N'物料圖片路徑',
    @level0type = N'SCHEMA',
    @level0name = N'dbo',
    @level1type = N'TABLE',
    @level1name = N'System',
    @level2type = N'COLUMN',
    @level2name = N'FabricPath'
GO
EXEC sp_addextendedproperty @name = N'MS_Description',
    @value = N'顏色圖片路徑',
    @level0type = N'SCHEMA',
    @level0name = N'dbo',
    @level1type = N'TABLE',
    @level1name = N'System',
    @level2type = N'COLUMN',
    @level2name = N'ColorPath'
GO
EXEC sp_addextendedproperty @name = N'MS_Description',
    @value = N'Nike 系統的廠代',
    @level0type = N'SCHEMA',
    @level0name = N'dbo',
    @level1type = N'TABLE',
    @level1name = N'System',
    @level2type = N'COLUMN',
    @level2name = N'NikeFactoryCode'
GO
EXEC sp_addextendedproperty @name = N'MS_Description',
    @value = N'Nike 標籤虛擬印表機 ( PDF )',
    @level0type = N'SCHEMA',
    @level0name = N'dbo',
    @level1type = N'TABLE',
    @level1name = N'System',
    @level2type = N'COLUMN',
    @level2name = N'NikeStickerPrintServer'
GO
EXEC sp_addextendedproperty @name = N'MS_Description',
    @value = N'Nike 標籤生成後下載的路徑',
    @level0type = N'SCHEMA',
    @level0name = N'dbo',
    @level1type = N'TABLE',
    @level1name = N'System',
    @level2type = N'COLUMN',
    @level2name = N'NikeStickerPrintFileFolder'
go
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'是否檢查AD帳號' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'System', @level2type=N'COLUMN',@level2name=N'IsLoginCheckADAccount'
GO
EXEC sp_addextendedproperty @name = N'MS_Description',
    @value = N'資料交換dummy Import檔案位置',
    @level0type = N'SCHEMA',
    @level0name = N'dbo',
    @level1type = N'TABLE',
    @level1name = N'System',
    @level2type = N'COLUMN',
    @level2name = N'ImportDataPathDummy'
GO
EXEC sp_addextendedproperty @name = N'MS_Description',
    @value = N'資料交換dummy import檔案名稱',
    @level0type = N'SCHEMA',
    @level0name = N'dbo',
    @level1type = N'TABLE',
    @level1name = N'System',
    @level2type = N'COLUMN',
    @level2name = N'ImportDataFileNameDummy'
GO
EXEC sp_addextendedproperty @name = N'MS_Description',
    @value = N'資料交換dummy 轉出檔案位置',
    @level0type = N'SCHEMA',
    @level0name = N'dbo',
    @level1type = N'TABLE',
    @level1name = N'System',
    @level2type = N'COLUMN',
    @level2name = N'ExportDataPathDummy'
GO
EXEC sp_addextendedproperty @name = N'MS_Description',
    @value = N'該工廠是否啟用OTP驗證功能',
    @level0type = N'SCHEMA',
    @level0name = N'dbo',
    @level1type = N'TABLE',
    @level1name = N'System',
    @level2type = N'COLUMN',
	@level2name = N'isNeedOTPFty'	
GO

EXEC sp_addextendedproperty @name = N'MS_Description',
    @value = N'該工廠是否啟用OTP驗證功能',
	@level0type = N'SCHEMA',
    @level0name = N'dbo',
    @level1type = N'TABLE',
    @level1name = N'System',
    @level2type = N'COLUMN',
	@level2name = N'isNeedOTPFty'
go
EXEC sp_addextendedproperty @name = N'MS_Description',
    @value = N'Formal的 FTP Port',
	@level0type = N'SCHEMA',
    @level0name = N'dbo',
    @level1type = N'TABLE',
    @level1name = N'System',
    @level2type = N'COLUMN',
    @level2name = N'FtpPort'
GO
EXEC sp_addextendedproperty @name = N'MS_Description',
    @value = N'SFTP IP',
    @level0type = N'SCHEMA',
    @level0name = N'dbo',
    @level1type = N'TABLE',
    @level1name = N'System',
    @level2type = N'COLUMN',
    @level2name = N'SFtpIP'
GO
EXEC sp_addextendedproperty @name = N'MS_Description',
    @value = N'Formal的SFTP連接埠',
    @level0type = N'SCHEMA',
    @level0name = N'dbo',
    @level1type = N'TABLE',
    @level1name = N'System',
    @level2type = N'COLUMN',
    @level2name = N'SFtpPort'
GO
EXEC sp_addextendedproperty @name = N'MS_Description',
    @value = N'SFTP ID',
    @level0type = N'SCHEMA',
    @level0name = N'dbo',
    @level1type = N'TABLE',
    @level1name = N'System',
    @level2type = N'COLUMN',
    @level2name = N'SFtpID'
GO
EXEC sp_addextendedproperty @name = N'MS_Description',
    @value = N'SFTP Passwor',
    @level0type = N'SCHEMA',
    @level0name = N'dbo',
    @level1type = N'TABLE',
    @level1name = N'System',
    @level2type = N'COLUMN',
    @level2name = N'SFtpPwd'
GO
EXEC sp_addextendedproperty @name = N'MS_Description',
    @value = N'Dummy的 SFTP IP',
    @level0type = N'SCHEMA',
    @level0name = N'dbo',
    @level1type = N'TABLE',
    @level1name = N'System',
    @level2type = N'COLUMN',
    @level2name = N'SFtpIPDummy'
GO
EXEC sp_addextendedproperty @name = N'MS_Description',
    @value = N'Dummy的 FTP 連接埠',
    @level0type = N'SCHEMA',
    @level0name = N'dbo',
    @level1type = N'TABLE',
    @level1name = N'System',
    @level2type = N'COLUMN',
    @level2name = N'FtpPortDummy'
GO
EXEC sp_addextendedproperty @name = N'MS_Description',
    @value = N'Dummy的 SFTP ID',
    @level0type = N'SCHEMA',
    @level0name = N'dbo',
    @level1type = N'TABLE',
    @level1name = N'System',
    @level2type = N'COLUMN',
    @level2name = N'SFtpIDDummy'
GO
EXEC sp_addextendedproperty @name = N'MS_Description',
    @value = N'Dummy的 SFTP Pwd',
    @level0type = N'SCHEMA',
    @level0name = N'dbo',
    @level1type = N'TABLE',
    @level1name = N'System',
    @level2type = N'COLUMN',
    @level2name = N'SFtpPwdDummy'

GO
EXEC sp_addextendedproperty @name = N'MS_Description',
    @value = N'Dummy的 SFTP PortIP',
    @level0type = N'SCHEMA',
    @level0name = N'dbo',
    @level1type = N'TABLE',
    @level1name = N'System',
    @level2type = N'COLUMN', 
    @level2name = N'SFtpPortDummy'
GO
EXEC sp_addextendedproperty @name = N'MS_Description',
    @value = N'Mercury Error Email 最後寄出日期',
    @level0type = N'SCHEMA',
    @level0name = N'dbo',
    @level1type = N'TABLE',
    @level1name = N'System',
    @level2type = N'COLUMN', 
    @level2name = N'MercuryErrorEmailLastDate'

GO
EXEC sp_addextendedproperty @name = N'MS_Description',
    @value = N'該區是否使用裁剪裁次要料',
    @level0type = N'SCHEMA',
    @level0name = N'dbo',
    @level1type = N'TABLE',
    @level1name = N'System',
    @level2type = N'COLUMN',
    @level2name = N'UseCutRefToRequestFabric'