CREATE TABLE [dbo].[WorkOrderRevisedMarkerOriginalData] (
    [ID]                  VARCHAR (13)   NOT NULL,
    [FactoryID]           VARCHAR (8)    NOT NULL,
    [MDivisionId]         VARCHAR (8)    NOT NULL,
    [SEQ1]                VARCHAR (3)    NOT NULL,
    [SEQ2]                VARCHAR (2)    NOT NULL,
    [CutRef]              VARCHAR (6)    NULL,
    [OrderID]             VARCHAR (13)   NULL,
    [CutplanID]           VARCHAR (13)   NULL,
    [Cutno]               NUMERIC (6)    NULL,
    [Layer]               NUMERIC (5)    NULL,
    [Colorid]             VARCHAR (6)    NULL,
    [Markername]          VARCHAR (20)   NULL,
    [EstCutDate]          DATE           NULL,
    [CutCellid]           VARCHAR (2)    NULL,
    [MarkerLength]        VARCHAR (15)   NULL,
    [ConsPC]              NUMERIC (6, 4) NULL,
    [Cons]                NUMERIC (9, 4) NULL,
    [Refno]               VARCHAR (20)   NULL,
    [SCIRefno]            VARCHAR (30)   NULL,
    [MarkerNo]            VARCHAR (10)   NULL,
    [MarkerVersion]       VARCHAR (3)    NULL,
    [Ukey]                BIGINT         IDENTITY (1, 1) NOT NULL,
    [Type]                VARCHAR (1)    NULL,
    [AddName]             VARCHAR (10)   NULL,
    [AddDate]             DATETIME       NULL,
    [EditName]            VARCHAR (10)   NULL,
    [EditDate]            DATETIME       NULL,
    [FabricCombo]         VARCHAR (2)    NULL,
    [MarkerDownLoadId]    VARCHAR (25)   NULL,
    [FabricCode]          VARCHAR (3)    NULL,
    [FabricPanelCode]     VARCHAR (2)    NULL,
    [Order_EachconsUkey]  BIGINT         NULL,
    [OldFabricUkey]       VARCHAR (10)   NULL,
    [OldFabricVer]        VARCHAR (2)    NULL,
    [ActCuttingPerimeter] NVARCHAR (15)  NULL,
    [StraightLength]      VARCHAR (15)   NULL,
    [CurvedLength]        VARCHAR (15)   NULL,
    [SpreadingNoID]       VARCHAR (3)    NULL,
    [WorkOrderUkey]       BIGINT         NULL,
    CONSTRAINT [PK_WorkOrderRevisedMarkerOriginalData] PRIMARY KEY CLUSTERED ([Ukey] ASC)
);

