CREATE NONCLUSTERED INDEX [Index_VNConsumption_Detail_Detail_v3] ON [dbo].[VNConsumption_Detail_Detail]
(
	[ID] ASC,
	[NLCode] ASC
)
INCLUDE([Waste]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]