Create view [dbo].[View_WH_Orders]
as
select [ID], [BrandID], [ProgramID], [StyleID], [SeasonID], [ProjectID], [Category], [OrderTypeID], [OrderCompanyID], [BuyMonth], [Dest]
	, [Model], [HsCode1], [HsCode2], [PayTermARID], [ShipTermID], [ShipModeList], [CdCodeID], [CPU], [Qty], [StyleUnit]
	, [PoPrice], [CFMPrice], [CurrencyID], [Commission], [FactoryID], [BrandAreaCode], [BrandFTYCode], [CTNQty], [CustCDID]
	, [CustPONo], [Customize1], [Customize2], [Customize3], [CFMDate], [BuyerDelivery], [SciDelivery], [SewInLine], [SewOffLine]
	, [CutInLine], [CutOffLine], [PulloutDate], [CMPUnit], [CMPPrice], [CMPQDate], [CMPQRemark], [EachConsApv], [MnorderApv]
	, [CRDDate], [InitialPlanDate], [PlanDate], [FirstProduction], [FirstProductionLock], [OrigBuyerDelivery], [ExCountry]
	, [InDCDate], [CFMShipment], [PFETA], [PackLETA], [LETA], [MRHandle], [SMR], [ScanAndPack], [VasShas], [SpecialCust]
	, [TissuePaper], [Junk], [Packing], [MarkFront], [MarkBack], [MarkLeft], [MarkRight], [Label], [OrderRemark], [ArtWorkCost]
	, [StdCost], [CtnType], [FOCQty], [SMnorderApv], [FOC], [MnorderApv2], [Packing2], [SampleReason], [RainwearTestPassed]
	, [SizeRange], [MTLComplete], [SpecialMark], [OutstandingRemark], [OutstandingInCharge], [OutstandingDate], [OutstandingReason]
	, [StyleUkey], [POID], [OrderComboID], [IsNotRepeatOrMapping], [SplitOrderId], [FtyKPI], [AddName], [AddDate], [EditName], [EditDate]
	, [SewLine], [ActPulloutDate], [ProdSchdRemark], [IsForecast], [LocalOrder], [GMTClose], [TotalCTN], [ClogCTN], [FtyCTN]
	, [PulloutComplete], [ReadyDate], [PulloutCTNQty], [Finished], [PFOrder], [SDPDate], [InspDate], [InspResult], [InspHandle]
	, [KPILETA], [MTLETA], [SewETA], [PackETA], [MTLExport], [DoxType], [FtyGroup], [MDivisionID], [CutReadyDate], [SewRemark]
	, [WhseClose], [SubconInSisterFty], [MCHandle], [LocalMR], [KPIChangeReason], [MDClose], [MDEditName], [MDEditDate]
	, [ClogLastReceiveDate], [CPUFactor], [SizeUnit], [CuttingSP], [IsMixMarker], [EachConsSource], [KPIEachConsApprove]
	, [KPICmpq], [KPIMNotice], [GMTComplete], [GFR], [CfaCTN], [DRYCTN], [PackErrCTN], [ForecastSampleGroup], [DyeingLoss]
	, [SubconInType], [LastProductionDate], [EstPODD], [AirFreightByBrand], [AllowanceComboID], [ChangeMemoDate], [BuyBack]
	, [BuyBackOrderID], [ForecastCategory], [OnSiteSample], [PulloutCmplDate], [NeedProduction], [IsBuyBack], [KeepPanels]
	, [BuyBackReason], [IsBuyBackCrossArticle], [IsBuyBackCrossSizeCode], [KpiEachConsCheck], [NonRevenue], [CAB], [FinalDest]
	, [Customer_PO], [AFS_STOCK_CATEGORY], [CMPLTDATE], [DelayCode], [DelayDesc], [HangerPack], [CDCodeNew], [SizeUnitWeight]
from DBO.Orders WITH (NOLOCK)
union ALL
select [ID], [BrandID], [ProgramID], [StyleID], [SeasonID], [ProjectID], [Category], [OrderTypeID], [OrderCompanyID], [BuyMonth], [Dest]
	, [Model], [HsCode1], [HsCode2], [PayTermARID], [ShipTermID], [ShipModeList], [CdCodeID], [CPU], [Qty], [StyleUnit]
	, [PoPrice], [CFMPrice], [CurrencyID], [Commission], [FactoryID], [BrandAreaCode], [BrandFTYCode], [CTNQty], [CustCDID]
	, [CustPONo], [Customize1], [Customize2], [Customize3], [CFMDate], [BuyerDelivery], [SciDelivery], [SewInLine], [SewOffLine]
	, [CutInLine], [CutOffLine], [PulloutDate], [CMPUnit], [CMPPrice], [CMPQDate], [CMPQRemark], [EachConsApv], [MnorderApv]
	, [CRDDate], [InitialPlanDate], [PlanDate], [FirstProduction], [FirstProductionLock], [OrigBuyerDelivery], [ExCountry]
	, [InDCDate], [CFMShipment], [PFETA], [PackLETA], [LETA], [MRHandle], [SMR], [ScanAndPack], [VasShas], [SpecialCust]
	, [TissuePaper], [Junk], [Packing], [MarkFront], [MarkBack], [MarkLeft], [MarkRight], [Label], [OrderRemark], [ArtWorkCost]
	, [StdCost], [CtnType], [FOCQty], [SMnorderApv], [FOC], [MnorderApv2], [Packing2], [SampleReason], [RainwearTestPassed]
	, [SizeRange], [MTLComplete], [SpecialMark], [OutstandingRemark], [OutstandingInCharge], [OutstandingDate], [OutstandingReason]
	, [StyleUkey], [POID], [OrderComboID], [IsNotRepeatOrMapping], [SplitOrderId], [FtyKPI], [AddName], [AddDate], [EditName], [EditDate]
	, [SewLine], [ActPulloutDate], [ProdSchdRemark], [IsForecast], [LocalOrder], [GMTClose], [TotalCTN], [ClogCTN], [FtyCTN]
	, [PulloutComplete], [ReadyDate], [PulloutCTNQty], [Finished], [PFOrder], [SDPDate], [InspDate], [InspResult], [InspHandle]
	, [KPILETA], [MTLETA], [SewETA], [PackETA], [MTLExport], [DoxType], [FtyGroup], [MDivisionID], [CutReadyDate], [SewRemark]
	, [WhseClose], [SubconInSisterFty], [MCHandle], [LocalMR], [KPIChangeReason], [MDClose], [MDEditName], [MDEditDate]
	, [ClogLastReceiveDate], [CPUFactor], [SizeUnit], [CuttingSP], [IsMixMarker], [EachConsSource], [KPIEachConsApprove]
	, [KPICmpq], [KPIMNotice], [GMTComplete], [GFR], [CfaCTN], [DRYCTN], [PackErrCTN], [ForecastSampleGroup], [DyeingLoss]
	, [SubconInType], [LastProductionDate], [EstPODD], [AirFreightByBrand], [AllowanceComboID], [ChangeMemoDate], [BuyBack]
	, [BuyBackOrderID], [ForecastCategory], [OnSiteSample], [PulloutCmplDate], [NeedProduction], [IsBuyBack], [KeepPanels]
	, [BuyBackReason], [IsBuyBackCrossArticle], [IsBuyBackCrossSizeCode], [KpiEachConsCheck], [NonRevenue], [CAB], [FinalDest]
	, [Customer_PO], [AFS_STOCK_CATEGORY], [CMPLTDATE], [DelayCode], [DelayDesc], [HangerPack], [CDCodeNew], [SizeUnitWeight]
from DBO.PMS_Orders_History WITH (NOLOCK)